import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {decodeTarget} from '../runtime/copy/decoder.mjs';
import {routePaths} from '../runtime/copy/smart-routes.mjs';
import {BSC} from '../core/copy/common.mjs';
const base=new URL('../docs/evidence/bnb-target/',import.meta.url);
const json=async name=>JSON.parse(await readFile(new URL(name,base),'utf8'));
// Recorded public RPC responses, NOT invented swaps and NOT live execution.
async function replay(files){const map=new Map();for(const name of files){const j=await json(name);for(const row of j.data??[]){if(row.params&&row.response)map.set(row.params[0].to.toLowerCase()+':'+row.params[0].data.toLowerCase(),row.response);}for(const req of j.request??[]){const res=j.response?.find(r=>r.id===req.id);if(res)map.set(req.params[0].to.toLowerCase()+':'+req.params[0].data.toLowerCase(),res);}}return {contract:async(to,abi,method,args=[])=>{let r=map.get(to.toLowerCase()+':'+abi.encodeFunctionData(method,args).toLowerCase());if(!r&&['getPair','getPool'].includes(method)){const reverse=[args[1],args[0],...args.slice(2)];r=map.get(to.toLowerCase()+':'+abi.encodeFunctionData(method,reverse).toLowerCase());}if(!r||r.error)throw Error('RECORDED_RPC_UNAVAILABLE');return abi.decodeFunctionResult(method,r.result);},call:async()=>{throw Error('TRACE_UNAVAILABLE_IN_CAPTURE');}};}
test('real 7BALL receipt authenticates Flap while never representing its launchpad as Pancake V2',async()=>{const j=await json('0x4f1caec89492578df33b2b1f7864d8155ac824a9c65f41fd66956630470dcb20.json');const rpc=await replay(['route-metadata.json','pool-authentication.json']);const d=await decodeTarget(rpc,j.transaction,j.receipt,j.block,j.target);assert.equal(d.kind,'BUY');assert.equal(d.protocol,'FLAP');assert.ok(d.quote_estimate);assert.equal(d.native_balance_evidence,false);assert.equal(d.token,'0x7f161c27dc558170f797d856539689b48ae47777');assert.ok(d.pools.some(p=>p.adapter==='FLAP_PORTAL'));assert.ok(d.pools.every(p=>p.adapter!=='PANCAKE_V2'));});
test('real Test receipt authenticates two V3 pools, exact received units, but no exact native price without trace',async()=>{const j=await json('0xba845a505ed4c648988d9c55435317fcef6014adb5cc3854c8e2b26b74f3c445.json');const rpc=await replay(['route-metadata-second.json','pool-authentication-second.json']);const d=await decodeTarget(rpc,j.transaction,j.receipt,j.block,j.target);assert.equal(d.kind,'BUY');assert.equal(d.symbol,'Test');assert.equal(d.quantity_raw,'46968969143457892020698');assert.equal(d.quote_raw,'10000000000000000');assert.ok(d.quote_estimate);assert.equal(d.native_balance_evidence,false);assert.equal(d.pools.length,2);assert.ok(d.pools.every(p=>p.adapter==='PANCAKE_V3'&&p.fee===10000));const buy=routePaths(d.pools,BSC.wbnb,d.token)[0],sell=routePaths(d.pools,d.token,BSC.wbnb)[0];assert.equal(buy.length,2);assert.equal(sell.length,2);assert.equal(buy[0].tokenIn,sell.at(-1).tokenOut);});
