import test from 'node:test';import assert from 'node:assert/strict';
import {BSC,PAIR} from '../core/copy/common.mjs';import {readPoolMetadata,MULTICALL_ABI,MULTICALL3} from '../runtime/copy/pool-metadata-batch.mjs';import {PaperDexRoute} from '../runtime/copy/paper-dex-route.mjs';
const pool='0x'+'12'.repeat(20),token='0x'+'34'.repeat(20),values={token0:BSC.wbnb,token1:token,factory:BSC.factory};
const rpc=()=>({cache:new Map(),context:{getStore:()=>({})},withContext:(_o,f)=>f(),multicallCodeVerified:Promise.resolve(true),calls:[],contract:async(_t,_a,m)=>[m==='getPair'?pool:values[m]],call:async function(m,params){this.calls.push({m,params});assert.equal(params[0].to,MULTICALL3);const [c]=MULTICALL_ABI.decodeFunctionData('aggregate3',params[0].data);assert.equal(c.length,4);return MULTICALL_ABI.encodeFunctionResult('aggregate3',[[...Object.entries(values).map(([m,v])=>[true,PAIR.encodeFunctionResult(m,[v])]),[false,'0x']]]);}});
test('batch metadata replaces three reads but still authenticates the canonical factory mapping',async()=>{const r=rpc();let registrations=0;r.contract=async(_t,_a,m)=>{assert.equal(m,'getPair');registrations++;return [pool];};const p=await new PaperDexRoute(r).pool({address:pool});assert.equal(p.adapter,'PANCAKE_V2');assert.equal(registrations,1);assert.equal(r.calls.length,1);assert.ok(r.cache.size>=5);});
test('batch results cannot authenticate a pool absent from the canonical registry',async()=>{const r=rpc();r.contract=async()=>['0x'+'00'.repeat(20)];const route=new PaperDexRoute(r);await assert.rejects(route.pool({address:pool}),/NOT_REGISTERED/);assert.equal(route.cache.size,0);});
test('unexpected Multicall bytecode retains legacy reads and verifies only once',async()=>{const r=rpc();delete r.multicallCodeVerified;let codeReads=0,legacy=0;r.call=async m=>{assert.equal(m,'eth_getCode');codeReads++;return '0x';};r.contract=async(_a,_b,m)=>{legacy++;return [values[m]];};await readPoolMetadata(r,pool);await readPoolMetadata(r,pool);assert.equal(codeReads,1);assert.equal(legacy,6);});
test('one aggregate RPC failure disables the optimization and preserves legacy reads',async()=>{const r=rpc();let batch=0,legacy=0;r.call=async()=>{batch++;throw Error('RPC_METHOD_UNAVAILABLE');};r.contract=async(_a,_b,m)=>{legacy++;return [values[m]];};await readPoolMetadata(r,pool);await readPoolMetadata(r,pool);assert.equal(batch,1);assert.equal(legacy,6);});
test('cancelled quote does not launch fallback reads or disable batching',async()=>{const r=rpc(),signal=AbortSignal.abort();r.context.getStore=()=>({signal});r.call=async()=>{throw Error('cancelled');};r.contract=async()=>{throw Error('unexpected fallback');};await assert.rejects(readPoolMetadata(r,pool),/cancelled/);assert.notEqual(r.poolMetadataBatch,false);});
