import test from 'node:test';
import assert from 'node:assert/strict';
import {mirrorRawAmount,validateSeededSell} from '../runtime/copy/shadow-sell-validation.mjs';
import {validateNetBuy,atomicShadowTemplate} from '../runtime/copy/shadow-validation.mjs';
import {SHADOW_WALLET} from '../runtime/copy/shadow-compare.mjs';
import {BSC,ERC20,hex} from '../core/copy/common.mjs';
import {FLAP} from '../runtime/copy/flap.mjs';
const token='0x'+'67'.repeat(20),c={max_slippage_bps:100,deadline_seconds:20},q={provider:'FLAP_PORTAL',side:'SELL',token,amount_raw:'500000',out_raw:'1000',min_out_raw:'990',slippage_bps:100,quoted_at:Date.now(),gas_price:'100',portal_state:{status:1}};
function fake({wrongDebit=false,gasFail=false,requireGas=0n,output=1000000n}={}){const seen=[];return {seen,rpc:{providers:[{id:'p',enabled:true}],verified:new Set(['p']),cooldown:new Map(),unsupported:new Map(),withContext:(_c,f)=>f(),request:async(_p,method,params)=>{seen.push({method,params});if(method==='eth_blockNumber')return '0x10';if(method==='eth_gasPrice')return '0x64';if(method==='eth_estimateGas'){if(gasFail)throw Error('execution reverted');return '0x30000';}assert.equal(method,'eth_simulateV1');assert.equal(params[1],'0x10');const state=params[0].blockStateCalls[0];assert.deepEqual(Object.keys(state.stateOverrides[SHADOW_WALLET]),['balance']);let owned=0n;return [{calls:state.calls.map(tx=>{if(tx.data.startsWith(ERC20.getFunction('balanceOf').selector))return {status:'0x1',returnData:hex(owned)};if(tx.data.startsWith(ERC20.getFunction('approve').selector))return {status:'0x1',returnData:hex(1),gasUsed:'0x1000'};const p=FLAP.parseTransaction(tx).args.params;if(BigInt(tx.value)>0n){owned+=output;return {status:'0x1',returnData:'0x',gasUsed:'0x20000'};}if(tx.gas&&BigInt(tx.gas)<requireGas)return {status:'0x0',returnData:'0x90b8ec18',gasUsed:tx.gas,error:{message:'execution reverted'}};owned-=p.inputAmount+(wrongDebit?1n:0n);const log=ERC20.encodeEventLog(ERC20.getEvent('Transfer'),[BSC.router,SHADOW_WALLET,2000n]);return {status:'0x1',returnData:'0x',gasUsed:'0x20000',logs:[{address:BSC.native,...log}]};})}];}}};}
test('raw partial and full target exits preserve integer sizing',()=>{assert.equal(mirrorRawAmount(1001n,1n,2n),500n);assert.equal(mirrorRawAmount(1001n,2n,2n),1001n);assert.throws(()=>mirrorRawAmount(1001n,3n,2n),/UNVERIFIED/);});
test('partial and full SHADOW SELL acquire actual simulated inventory then prove debit, proceeds and gas',async()=>{
 for(const qty of ['500','1000']){const e=fake(),r=await validateSeededSell(e,{hash:'h',token,side:'SELL',quantity_raw:qty,target_balance_before:'1000'},q,c);assert.equal(r.status,'SIMULATED');assert.equal(r.simulation.sold_raw,qty==='500'?'500000':'1000000');assert.equal(r.simulation.remaining_raw,qty==='500'?'500000':'0');assert.equal(r.simulation.full_exit,qty==='1000');assert.equal(r.signed,false);assert.equal(r.broadcast,false);assert.equal(r.quote.min_out_raw,'1980');assert.equal(e.seen.filter(x=>x.method==='eth_simulateV1').length,5);assert.ok(e.seen.at(-1).params[0].blockStateCalls[0].calls[4].gas);}
});
test('SHADOW SELL refuses false inventory and balance conservation errors',async()=>{const r=await validateSeededSell(fake({wrongDebit:true}),{hash:'h',token,side:'SELL',quantity_raw:'500',target_balance_before:'1000'},q,c);assert.equal(r.status,'FAILED');assert.match(r.failure.reason,/TOKEN_DEBIT/);assert.equal(r.failure.category,'SIMULATION_ENVIRONMENT');});
test('SHADOW BUY quotes actual net output with unchanged input and slippage, and requires gas success',async()=>{
 const buy={...q,side:'BUY',amount_raw:'2000000000000000',out_raw:'1100000',min_out_raw:'1089000'},e=fake(),r=await validateNetBuy(e,{hash:'h',token},buy,c);assert.equal(r.status,'SIMULATED');assert.equal(r.quote.out_raw,'1000000');assert.equal(r.quote.min_out_raw,'990000');assert.equal(r.amount_raw,buy.amount_raw);assert.equal(buy.min_out_raw,'1089000');assert.equal(r.slippage_bps,100);assert.equal(r.simulation.final_minimum_uses_unchanged_slippage_bps,100);assert.equal(e.seen.length,4);
 const failed=await validateNetBuy(fake({gasFail:true}),{hash:'h',token},buy,c);assert.equal(failed.status,'FAILED');assert.equal(failed.failure.category,'ROUTER_REVERT');
});
test('unsupported SHADOW route remains explicit and cannot spend RPC without a compatible observed V2 edge',async()=>{const e=fake();await assert.rejects(atomicShadowTemplate(e,{...q,provider:'PAPER_DEX_PATH',hops:[{adapter:'UNISWAP_V3'},{adapter:'PANCAKE_V3'}]},c),/NO_ATOMIC_BUILDER/);assert.equal(e.seen.length,0);});

test('seeded gas search retains a successful bound when a lower gas trial reverts',async()=>{const r=await validateSeededSell(fake({requireGas:2000000n}),{hash:'h',token,side:'SELL',quantity_raw:'500',target_balance_before:'1000'},q,c);assert.equal(r.status,'SIMULATED');assert.ok(BigInt(r.unsigned_transaction.gas)>=2000000n);assert.ok(r.gas_search.some(x=>x.status==='FAIL'&&x.failure.root_cause==='GAS_LIMIT_TOO_LOW_AT_IDENTICAL_PINNED_STATE'));});
