import test from 'node:test';
import assert from 'node:assert/strict';
import {BscRpc} from '../runtime/copy/rpc.mjs';
import {RpcTelemetry} from '../runtime/copy/rpc-telemetry.mjs';
import {copyEnvironment,historyReadProviders} from '../runtime/copy/provider-config.mjs';
import {WalletActivityProvider} from '../runtime/copy/activity-provider.mjs';
import {Store} from '../core/store.mjs';
import {sqliteDriver} from '../runtime/sqlite.mjs';
import {CopyEngine} from '../runtime/copy/engine.mjs';
import {blockWork} from '../runtime/copy/block-worker.mjs';
import {ERC20,decode} from '../core/copy/common.mjs';
const providers=['primary','secondary'].map(role=>({id:role,role,enabled:true,http_url:'https://'+role+'.invalid'}));
const response=result=>new Response(JSON.stringify({result}));

test('NodeReal quota messages open the circuit and count as quota failures',async()=>{for(const message of ['You have reached the maximum API usage limit','ran out of cu']){let primary=0;const rpc=new BscRpc(providers,{fetcher:async url=>{if(url.includes('primary')){primary++;return new Response(JSON.stringify({error:{code:-32005,message}}));}return response('0x1');}});providers.forEach(p=>rpc.verified.add(p.id));await rpc.call('eth_blockNumber');await rpc.call('eth_blockNumber');assert.equal(primary,1);assert.equal(rpc.telemetry.snapshot(providers).providers[0].rate_limits,1);}});

test('NodeReal secondary subscribes only to heads and counts WS bandwidth',()=>{const provider=copyEnvironment({BSC_FREE_BASELINE:'1'}).providers.find(p=>p.id==='free-nodereal'),rpc=new BscRpc([provider]);const p=new WalletActivityProvider(provider,rpc,[{address:'0x'+'12'.repeat(20)}],()=>{},()=>{});const sent=[];p.socket={readyState:1,send:body=>sent.push(JSON.parse(body))};p.requests.set(1,'chain');p.message({id:1,result:'0x38'});assert.equal(sent.length,1);assert.deepEqual(sent[0].params,['newHeads']);p.message({id:sent[0].id,result:'heads'});const msg={method:'eth_subscription',params:{subscription:'heads',result:{number:'0x10'}}};p.message(msg);const s=rpc.telemetry.snapshot([provider]);assert.equal(s.providers[0].bytes,Buffer.byteLength(JSON.stringify(msg)));assert.ok(s.providers[0].daily_units_estimated>20);});
test('100 healthy reads use 100 wire requests, not 200 eager duplicate requests',async()=>{let count=0;const rpc=new BscRpc(providers,{fetcher:async()=>{count++;return response('0x1');}});providers.forEach(p=>rpc.verified.add(p.id));for(let n=0;n<100;n++)await rpc.call('eth_blockNumber');assert.equal(count,100);assert.equal(rpc.failover.attempts,0);});
test('daily quota error in a JSON-RPC HTTP 200 trips the circuit; all subsequent reads use the free fallback',async()=>{const sent=[];const rpc=new BscRpc(providers,{fetcher:async url=>{sent.push(url);return url.includes('primary')?responseError():response('0x123');}});function responseError(){return new Response(JSON.stringify({error:{code:-32003,message:'daily request limit reached'}}));}providers.forEach(p=>rpc.verified.add(p.id));for(let n=0;n<20;n++)assert.equal(await rpc.call('eth_blockNumber'),'0x123');assert.equal(sent.filter(s=>s.includes('primary')).length,1);assert.equal(sent.filter(s=>s.includes('secondary')).length,20);assert.ok(rpc.cooldown.get('primary')>Date.now()+3500000);assert.equal(rpc.telemetry.snapshot(providers).providers[0].rate_limits,1);assert.equal(rpc.failover.successes,20);});
test('HTTP 429 fails over, retaining its daily-quota reason instead of retrying a blocked endpoint',async()=>{const rpc=new BscRpc(providers,{fetcher:async url=>url.includes('primary')?new Response(JSON.stringify({error:{message:'daily request limit reached'}}),{status:429}):response('0x1')});providers.forEach(p=>rpc.verified.add(p.id));assert.equal(await rpc.call('eth_blockNumber'),'0x1');assert.match(rpc.metrics.find(m=>m.provider==='primary').error,/daily request limit/);});
test('each provider is tried at most once when every endpoint fails',async()=>{let count=0;const rpc=new BscRpc(providers,{fetcher:async()=>{count++;throw Error('network failure');}});providers.forEach(p=>rpc.verified.add(p.id));await assert.rejects(rpc.call('eth_blockNumber'));await assert.rejects(rpc.call('eth_blockNumber'),/DEGRADED/);assert.equal(count,2);});
test('token metadata concurrent reads are coalesced and cached; live balances never share that cache',async()=>{let count=0;const rpc=new BscRpc([providers[0]],{fetcher:async(_u,{body})=>{count++;const data=JSON.parse(body).params[0].data;return response(ERC20.encodeFunctionResult(data.startsWith(ERC20.getFunction('decimals').selector)?'decimals':'balanceOf',[18]));}});rpc.verified.add('primary');const token='0x'+'12'.repeat(20);await Promise.all(Array.from({length:20},()=>rpc.contract(token,ERC20,'decimals')));await rpc.contract(token,ERC20,'decimals');assert.equal(count,1);await rpc.contract(token,ERC20,'balanceOf',[token]);await rpc.contract(token,ERC20,'balanceOf',[token]);assert.equal(count,3);assert.equal(rpc.telemetry.snapshot(providers).cache.hits,20);});
test('backfill cannot borrow live quota even if no archive exists',async()=>{assert.deepEqual(historyReadProviders(providers),[]);let count=0;const rpc=new BscRpc(providers,{pipeline:'HISTORICAL_BACKFILL_PIPELINE',fetcher:async()=>{count++;return response('0x38');}});await assert.rejects(rpc.call('eth_chainId'),/SEPARATE_QUOTA/);assert.equal(count,0);});
test('known daily quota pauses backfill at 80 percent before the next network call, including after restoring counters',async()=>{let clock=Date.now(),count=0;const p={...providers[0],history_dedicated:true,daily_credit_limit:100,credit_unit:20};const telemetry=new RpcTelemetry({now:()=>clock});for(let n=0;n<4;n++)telemetry.add(p.id,'eth_call',{pipeline:'HISTORICAL_BACKFILL_PIPELINE',units:20});const rpc=new BscRpc([p],{telemetry:new RpcTelemetry({saved:telemetry.snapshot([p])}),pipeline:'HISTORICAL_BACKFILL_PIPELINE',fetcher:async()=>{count++;return response('0x1');}});rpc.verified.add(p.id);await assert.rejects(rpc.call('eth_blockNumber'),/80_PERCENT/);assert.equal(count,0);});
test('telemetry separates HTTP, WS notifications, provider, method, timeouts and rolling windows',()=>{let now=Date.UTC(2026,8,10,0,0,0);const t=new RpcTelemetry({now:()=>now});t.add('p','eth_call');t.add('p','eth_subscription:pending-full',{transport:'WS',notification:true,bytes:123});t.outcome('p','eth_call',{error:'timeout'});t.cache(true);t.cache(false);let s=t.snapshot([{id:'p'}]);assert.equal(s.providers[0].requests,1);assert.equal(s.providers[0].notifications,1);assert.equal(s.providers[0].timeouts,1);assert.equal(s.cache.hit_rate,.5);now+=61000;s=t.snapshot([{id:'p'}]);assert.equal(s.providers[0].requests_min,0);assert.equal(s.providers[0].requests_hour,1);});
test('hash-only pending stream never triggers unrelated HTTP transaction lookups',async()=>{let sent=0;const p=new WalletActivityProvider({id:'p'},{call:async()=>sent++},[],()=>{},()=>{});for(let n=0;n<1000;n++)await p.pending('0x'+'a'.repeat(64),Date.now(),performance.now());assert.equal(sent,0);assert.equal(p.pendingSkipped,1000);});
test('a metered unfiltered pending subscription requires explicit budget opt-in',()=>{const env=copyEnvironment({BSC_PRIMARY_HTTP:'https://unit.bsc.quiknode.pro/private',BSC_PRIMARY_WS:'wss://unit.bsc.quiknode.pro/private',BSC_PRIMARY_PENDING:'STANDARD_FULL'});const p=new WalletActivityProvider(env.providers[0],{},[],()=>{},()=>{});let sent=0;p.send=()=>sent++;p.subscribePending();assert.equal(sent,0);assert.equal(p.subscriptionErrors.get('pending'),'DISABLED_UNFILTERED_METERED_STREAM');});
test('free baseline excludes saved paid endpoints and configures independent public fallbacks',()=>{const {providers:p}=copyEnvironment({BSC_FREE_BASELINE:'1',BSC_PRIMARY_HTTP:'https://unit.bsc.quiknode.pro/private'});assert.equal(p.length,4);assert.equal(p.find(x=>x.role==='secondary').id,'free-nodereal');assert.equal(p.find(x=>x.id==='free-nodereal').requests_per_second,1);assert.ok(p.every(p=>p.public_free));assert.equal(p.filter(p=>p.ws_url).length,2);assert.deepEqual(historyReadProviders(p),[]);});
test('fresh window skips the old 80000-block hole but recovers every missed head inside the current window',async t=>{const db=sqliteDriver(':memory:'),store=new Store(db,{encryptionKey:Buffer.alloc(32,1).toString('base64')});await store.init();t.after(()=>db.close());const e=new CopyEngine(store);e.targets=[];const requested=[];e.rpc={call:async(_m,[tag])=>{const n=Number(BigInt(tag));requested.push(n);return {number:tag,hash:'h'+n,parentHash:'h'+(n-1),timestamp:'0x1',transactions:[]};}};await store.set('engine_desired','RUNNING');await store.set('copy_config',{...await store.setting('copy_config'),enabled:true});await store.set('copy_cursor',1);const head=n=>e.observe({kind:'head',provider:'free',method:'WEBSOCKET',received_at:Date.now(),event:{number:'0x'+n.toString(16)}});await head(80000);await blockWork(e,false);await head(80003);await blockWork(e,false);await blockWork(e,false);await blockWork(e,false);assert.equal(await store.setting('copy_live_cursor'),80003);assert.deepEqual(requested.slice().sort(),[80000,80001,80002,80003]);assert.equal(await store.setting('copy_cursor'),1);assert.equal(await blockWork(e,true),false);});
