import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../core/store.mjs';import {sqliteDriver} from '../runtime/sqlite.mjs';import {defaults} from '../core/schema.mjs';import {evaluateRisk,validateQuote} from '../core/risk.mjs';import {allocateSell,accountExecution} from '../core/accounting.mjs';import {commitPaperBuy,commitPaperSell} from '../core/paper-ledger.mjs';import {baseline,pastOnly,simulateBacktest,saveStrategy} from '../core/strategy.mjs';import {solanaFlows} from '../core/traders.mjs';import {USDC} from '../core/providers/chains.mjs';import {encrypt,decrypt,decimalToRaw,validateEndpoint} from '../core/util.mjs';import {handle} from '../core/service.mjs';
async function memory(){const s=new Store(sqliteDriver(':memory:'));await s.init();return s;}
const context=()=>({policy:structuredClone(defaults.policy),enabled:true,epoch:0,order:{epoch:0,side:'BUY',notional_cents:100},market:{price:1,liquidity:30000,received_at:Date.now()},health:{status:'CONNECTED',last_success:Date.now()}});
test('base units remain exact above Number safe integer',()=>{assert.equal(decimalToRaw('123456789.123456789',9),'123456789123456789');assert.throws(()=>decimalToRaw('1.001',2));});
test('risk rejects unknown data, stale state, capital, daily loss and drawdown',()=>{const c=context();assert.deepEqual(evaluateRisk(c),[]);assert.ok(evaluateRisk({...c,enabled:false}).includes('TRADING_DISABLED'));assert.ok(evaluateRisk({...c,epoch:1}).includes('STALE_TRADING_EPOCH'));assert.ok(evaluateRisk({...c,exposure:1000}).includes('HARD_CAPITAL_LIMIT'));assert.ok(evaluateRisk({...c,loss:1000}).includes('DAILY_LOSS_LIMIT'));assert.ok(evaluateRisk({...c,drawdownPct:11}).includes('MAX_DRAWDOWN'));assert.ok(evaluateRisk({...c,valuationUnknown:true}).includes('POSITION_VALUATION_UNKNOWN'));assert.ok(evaluateRisk({...c,market:null}).includes('STALE_OR_UNKNOWN_PRICE'));});
test('closing sell is not blocked by entry exposure/position/loss limits',()=>{const c=context();const errors=evaluateRisk({...c,order:{...c.order,side:'SELL',notional_cents:1000},exposure:1000,positions:5,loss:1000,drawdownPct:20});assert.deepEqual(errors,[]);});
test('quote enforces actual minimum output, not only displayed bps',()=>{const q={outAmount:'10000',minOut:'9900',slippageBps:100,priceImpactPct:.2,quotedAt:Date.now()};assert.deepEqual(validateQuote(q,defaults.policy),[]);assert.ok(validateQuote({...q,minOut:'1'},defaults.policy).includes('INVALID_MINIMUM_OUTPUT'));assert.ok(validateQuote({...q,quotedAt:0},defaults.policy).includes('QUOTE_EXPIRED'));assert.ok(validateQuote({...q,priceImpactPct:null},defaults.policy).includes('PRICE_IMPACT_UNKNOWN_OR_HIGH'));});
test('persistent database and kill switch survive restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'memelab-'));try{let d=sqliteDriver(join(dir,'db'));let s=new Store(d);await s.init();const v=await saveStrategy(s,'Fixture strategy',baseline);await s.set('trading_enabled',true);await s.stop();d.close();d=sqliteDriver(join(dir,'db'));s=new Store(d);assert.equal(await s.setting('trading_enabled'),false);assert.equal(await s.setting('epoch'),1);assert.equal((await s.get('SELECT id FROM strategy_versions WHERE id=?',v)).id,v);d.close();}finally{await rm(dir,{recursive:true,force:true});}});
test('SQL batch rolls back all mutations on failure',async()=>{const s=await memory();await assert.rejects(s.batch([["INSERT INTO notes VALUES ('a','token','x','test',NULL,1)",[]],["INSERT INTO notes VALUES ('a','token','x','duplicate',NULL,1)",[]]]));assert.equal((await s.get('SELECT COUNT(*) n FROM notes')).n,0);});
test('immutable strategy versions do not overwrite predecessor',async()=>{const s=await memory();const v=await saveStrategy(s,'Fixture',baseline);const old=await s.get('SELECT * FROM strategy_versions WHERE id=?',v);await saveStrategy(s,'Fixture',{...baseline,min_liquidity:30000},old.strategy_id);assert.equal((await s.get('SELECT COUNT(*) n FROM strategy_versions')).n,2);assert.equal(JSON.parse((await s.get('SELECT parameters FROM strategy_versions WHERE id=?',v)).parameters).min_liquidity,15000);});
test('pretrade access excludes observed or received future records',()=>{const rows=[{observed_at:1,received_at:1},{observed_at:2,received_at:11},{observed_at:12,received_at:2}];assert.equal(pastOnly(rows,10).length,1);});
test('backtest cannot fill on signal snapshot itself',()=>{const sample={chain:'solana',token_id:'fixture',received_at:1000,observed_at:1000,price:1,liquidity:30000,market_cap:50000,volume_5m:20000,buys_5m:30,sells_5m:10,change_5m:5,pool_created:1};const out=simulateBacktest([sample],baseline,{capital_cents:10000,order_cents:200,fee_bps:30,slippage_bps:100,network_fee_cents:3,latency_ms:100,max_impact_pct:2});assert.equal(out.open_positions,0);assert.equal(out.sample_size,0);});
test('wallet transfers without opposing quote asset are not labeled buys',()=>{const tx={meta:{preTokenBalances:[],postTokenBalances:[{owner:'fixture',mint:'TOKEN',uiTokenAmount:{amount:'100',decimals:6}}]}};assert.equal(solanaFlows(tx,'fixture')[0].side,'TOKEN_FLOW');});
test('FIFO sale conserves token units and cost across partial positions',()=>{const r=allocateSell([{id:'a',quantity_raw:'100',cost_cents:1000},{id:'b',quantity_raw:'100',cost_cents:2000}],'150',2500,10);assert.equal(r.cost_cents,2000);assert.equal(r.pnl_cents,490);assert.equal(r.updates[1].quantity_raw,'50');assert.equal(r.updates[1].cost_cents,1000);assert.throws(()=>allocateSell([{id:'a',quantity_raw:'1',cost_cents:1}],'2',5,1));});
test('API secrets encrypted with authenticated encryption',async()=>{const key=Buffer.alloc(32,7).toString('base64');const text=await encrypt('fixture-secret',key);assert.ok(!text.includes('fixture-secret'));assert.equal(await decrypt(text,key),'fixture-secret');await assert.rejects(decrypt(text,Buffer.alloc(32,8).toString('base64')));});
test('RPC URL allowlist rejects SSRF targets and arbitrary domains',()=>{assert.throws(()=>validateEndpoint('http://127.0.0.1'));assert.throws(()=>validateEndpoint('https://api.mainnet-beta.solana.com.attacker.example'));assert.throws(()=>validateEndpoint('https://user:password@api.mainnet-beta.solana.com'));assert.equal(validateEndpoint('https://api.mainnet-beta.solana.com'),'https://api.mainnet-beta.solana.com');});
async function paperFixture(cash=200){const s=await memory();const now=Date.now();await s.run('INSERT INTO tokens VALUES (?,?,?,?,?,?,?)','solana:fixture','solana','fixture','FIX','Test fixture',6,now);await s.run('INSERT INTO runs VALUES (?,?,?,?,?,?,?,?,?)','run','PAPER','RUNNING',cash,cash,null,JSON.stringify({reserve_pct:0}),now,null);await s.set('trading_enabled',true);return {s,run:{id:'run',capital_cents:cash,version_id:null,config:{reserve_pct:0}},token:{id:'solana:fixture',address:'fixture',decimals:6},tradeId:'paper-fixture',quantity:'1000000',price:1,quote:{inputMint:USDC,inAmount:'1000000',outputMint:'fixture',outAmount:'1000000',minOut:'990000'},cost:203,now};}
test('paper does not create position when cash cannot cover fees',async()=>{const f=await paperFixture();assert.equal(await commitPaperBuy(f.s,f),false);assert.equal((await f.s.get('SELECT COUNT(*) n FROM positions')).n,0);assert.equal((await f.s.get("SELECT cash_cents FROM runs WHERE id='run'")).cash_cents,200);});
test('paper buy/sell book atomically and do not double-credit exit',async()=>{const f=await paperFixture(1000);assert.equal(await commitPaperBuy(f.s,f),true);assert.equal((await f.s.get("SELECT cash_cents FROM runs WHERE id='run'")).cash_cents,797);const position=await f.s.get('SELECT * FROM positions WHERE id=?',f.tradeId);const sale={...f,position,tradeId:'sell-fixture',proceeds:250,quote:{...f.quote,inputMint:'fixture',outputMint:USDC}};assert.equal(await commitPaperSell(f.s,sale),true);assert.equal((await f.s.get("SELECT cash_cents FROM runs WHERE id='run'")).cash_cents,1047);assert.equal(await commitPaperSell(f.s,{...sale,tradeId:'sell-again'}),false);assert.equal((await f.s.get("SELECT cash_cents FROM runs WHERE id='run'")).cash_cents,1047);});
test('emergency stop blocks later paper fills',async()=>{const f=await paperFixture(1000);await f.s.stop();assert.equal(await commitPaperBuy(f.s,f),false);});
test('state and exports have no synthetic initial records or secrets',async()=>{const s=await memory();await s.set('secrets',{jupiterKey:'encrypted-fixture'});const state=await handle(s,'state','GET',{},{});assert.deepEqual(state.tokens,[]);assert.deepEqual(state.orders,[]);assert.equal(state.validation.status,'NOT_PRODUCTION_VALIDATED');const exp=await handle(s,'export','GET',{},{});assert.ok(!JSON.stringify(exp).includes('encrypted-fixture'));});
test('LIVE AUTO remains blocked without on-chain validation',async()=>{const s=await memory();await s.set('execution_wallets',{solana:'fixture'});await assert.rejects(handle(s,'mode','POST',{mode:'LIVE_AUTO',ack:'ENABLE LIVE MONEY'},{encryptionKey:'fixture'}),/LIVE_AUTO_LOCKED/);});
