import {verifySmartTransaction} from '../core/copy/smart-router.mjs';
// Dedicated child process. Only encrypted, persisted, policy-checked orders may be signed.
import {readFile,stat} from 'node:fs/promises';
import {Wallet,Transaction,keccak256} from 'ethers';
import {runtimeContext} from './context.mjs';
import {assertCopyFence,capitalCheck} from '../core/copy/execution-policy.mjs';
import {BSC,ROUTER,ERC20,addr,check,decode,encode,cleanError} from '../core/copy/common.mjs';
import {encrypt} from '../core/util.mjs';
const context=await runtimeContext(),store=context.store;let signer=null;
try{if(process.env.BNB_KEYSTORE_FILE&&process.env.BNB_PASSWORD_FILE){for(const file of [process.env.BNB_KEYSTORE_FILE,process.env.BNB_PASSWORD_FILE]){const s=await stat(file);check(process.platform==='win32'||(s.mode&0o077)===0,'BNB_SECRET_FILE_PERMISSIONS');}const password=(await readFile(process.env.BNB_PASSWORD_FILE,'utf8')).trim();signer=await Wallet.fromEncryptedJson(await readFile(process.env.BNB_KEYSTORE_FILE,'utf8'),password);}}catch(e){process.send?.({type:'ready',status:'ERROR',error:cleanError(e)});}
if(signer)process.send?.({type:'ready',status:'CONNECTED',address:signer.address});else process.send?.({type:'ready',status:'NOT_CONFIGURED',address:null});
let busy=false;process.on('message',async message=>{if(message?.type!=='sign')return;const respond=msg=>process.send?.({request_id:message.request_id,...msg});if(busy)return respond({error:'SIGNER_BUSY'});busy=true;const signStart=performance.now();try{check(signer,'SIGNER_NOT_CONFIGURED');const a=await store.get('SELECT * FROM copy_actions WHERE id=?',message.id);check(a&&a.state==='PROCESSING'&&a.mode.startsWith('LIVE'),'ORDER_NOT_SIGNABLE');const {config,target}=await assertCopyFence(store,a,{signing:true});check(addr(config.execution_wallet)===addr(signer.address),'WRONG_EXECUTION_WALLET');const d=decode(a.data),u=d.unsigned,q=d.quote;check(u&&q,'BUILD_MISSING');check(Date.now()-q.quoted_at<=config.max_quote_age_ms,'QUOTE_EXPIRED');check(d.safety?.status==='PASSED'||a.side==='SELL','SAFETY_REQUIRED');check(Number(u.chainId)===56,'WRONG_CHAIN');check(Date.now()/1000<d.build.deadline,'TX_DEADLINE');check(d.simulation?.success===true,'SIMULATION_REQUIRED');if(a.mode==='LIVE_APPROVAL'){const v=d.approved_intent;check(v&&v.token===a.token&&v.side===a.side&&v.epoch===a.epoch&&v.amount_raw===a.amount_raw&&v.provider===q.provider&&addr(v.wallet)===addr(signer.address)&&Date.now()<=v.expires_at&&BigInt(q.min_out_raw)>=BigInt(v.min_out_raw),'APPROVAL_INTENT_MISMATCH');}const to=addr(u.to);check(['PANCAKE_V2','PANCAKE_SMART'].includes(q.provider),'LIVE_ROUTE_NOT_VALIDATED');const spender=q.provider==='PANCAKE_SMART'?BSC.smartRouter:BSC.router;if(q.provider==='PANCAKE_SMART')check(d.safety?.buy_tax===0&&d.safety?.sell_tax===0,'SMART_TAX_NOT_ZERO');
 if(d.approval_tx){check(a.side==='SELL'&&[0n,BigInt(a.amount_raw)].includes(BigInt(d.approval_amount_raw)),'APPROVAL_SIZE_OR_SIDE_MISMATCH');check(to===addr(a.token),'APPROVAL_TOKEN_MISMATCH');const p=ERC20.parseTransaction({data:u.data,value:u.value});check(p.name==='approve'&&addr(p.args[0])===spender&&BigInt(p.args[1])===BigInt(d.approval_amount_raw),'APPROVAL_MISMATCH');check(BigInt(u.value)===0n,'APPROVAL_WITH_VALUE');}
 else if(q.provider==='PANCAKE_SMART'){check(q.token===a.token&&q.side===a.side,'SMART_ORDER_ASSET_MISMATCH');verifySmartTransaction(u,q,signer.address,d.build.deadline);check(q.amount_raw===a.amount_raw,'SMART_AMOUNT_MISMATCH');}
 else{check(to===BSC.router,'ROUTER_NOT_ALLOWED');const p=ROUTER.parseTransaction({data:u.data,value:u.value});const buy=a.side==='BUY';check(p.name===(buy?'swapExactETHForTokensSupportingFeeOnTransferTokens':'swapExactTokensForETHSupportingFeeOnTransferTokens'),'SWAP_METHOD_MISMATCH');const path=p.args[buy?1:2].map(addr),recipient=addr(p.args[buy?2:3]),deadline=Number(p.args[buy?3:4]);check(recipient===addr(signer.address)&&deadline===d.build.deadline,'RECIPIENT_OR_DEADLINE_MISMATCH');check(path[0]===(buy?BSC.wbnb:a.token)&&path.at(-1)===(buy?a.token:BSC.wbnb),'SWAP_ASSET_MISMATCH');check(BigInt(p.args[buy?0:1])===BigInt(q.min_out_raw),'MINIMUM_OUTPUT_MISMATCH');check(BigInt(u.value)===(buy?BigInt(a.amount_raw):0n),'SWAP_VALUE_MISMATCH');if(!buy)check(BigInt(p.args[0])===BigInt(a.amount_raw),'SWAP_AMOUNT_MISMATCH');}
 const fee=BigInt(u.gasLimit)*BigInt(u.gasPrice);await capitalCheck(store,a,a.amount_raw,fee,config,target);const payload=await signer.signTransaction(u);const tx=Transaction.from(payload);check(tx.from.toLowerCase()===addr(config.execution_wallet),'SIGNATURE_RECOVERY_MISMATCH');await assertCopyFence(store,a,{signing:true});d.signed=await encrypt(payload,context.encryptionKey);d.signed_at=Date.now();d.sign_ms=performance.now()-signStart;const hash=keccak256(payload);const result=await store.run("UPDATE copy_actions SET state='SIGNED',hash=?,nonce=?,updated_at=?,data=? WHERE id=? AND state='PROCESSING' AND epoch=(SELECT json_extract(value,'$.epoch') FROM settings WHERE key='copy_config') AND (SELECT json_extract(value,'$.enabled') FROM settings WHERE key='copy_config')=1",hash,tx.nonce,Date.now(),encode(d),a.id);check(result.changes===1,'STOPPED_DURING_SIGNING');respond({hash});}catch(e){respond({error:cleanError(e)});}finally{busy=false;}});
process.on('disconnect',()=>{context.db.close();process.exit(0);});
