import {parentPort,workerData} from 'node:worker_threads';
import {DatabaseSync} from 'node:sqlite';
import {wei,bnb} from '../core/copy/common.mjs';
import {summarizeProfiles,compareTrade} from '../core/copy/latency-profile.mjs';
import {eventHistory} from '../core/dashboard-history.mjs';
import {state} from '../core/service.mjs';
const db=new DatabaseSync(workerData.filename,{readOnly:true});
db.exec('PRAGMA busy_timeout=100;');
const setting=k=>JSON.parse(db.prepare('SELECT value FROM settings WHERE key=?').get(k)?.value??'null');
const readStore={options:workerData.options??{},setting:async k=>setting(k),get:async(sql,...args)=>db.prepare(sql).get(...args),all:async(sql,...args)=>db.prepare(sql).all(...args)};
let bootstrapFlight=null;
parentPort.on('message',async m=>{if(!['history','bootstrap'].includes(m.kind))return;try{let result;if(m.kind==='bootstrap'){bootstrapFlight??=state(readStore,workerData.options??{}).then(value=>JSON.stringify(value)).finally(()=>{bootstrapFlight=null;});result=await bootstrapFlight;}else result=await eventHistory(readStore,m.options);parentPort.postMessage({requestId:m.requestId,result});}catch(e){parentPort.postMessage({requestId:m.requestId,error:e.message});}});
function publish(){try{db.exec('BEGIN');
 const runtime=setting('copy_runtime')??{};
 // Scalar projections never load nested RPC history or raw transactions.
 const actions=db.prepare("SELECT id,event_id,target_id,mode,side,token,state,created_at,updated_at,error,amount_raw,hash,json_object('copy_status',json_extract(data,'$.copy_status'),'paper_reaction_ms',json_extract(data,'$.paper_reaction_ms'),'quote_ms',json_extract(data,'$.quote_ms'),'event',json_object('symbol',json_extract(data,'$.event.symbol'))) data FROM copy_actions ORDER BY created_at DESC LIMIT 30").all().map(r=>({...r,data:JSON.parse(r.data)}));
 const events=db.prepare("SELECT id,target_id,hash,kind,status,detected_at,block,json_object('token',json_extract(data,'$.token'),'symbol',json_extract(data,'$.symbol'),'side',json_extract(data,'$.side'),'quote_token',json_extract(data,'$.quote_token'),'sold_fraction',json_extract(data,'$.sold_fraction'),'history',json_extract(data,'$.history'),'protocol',json_extract(data,'$.protocol'),'target_at',json_extract(data,'$.target_at'),'quote_raw',json_extract(data,'$.quote_raw'),'quantity_raw',json_extract(data,'$.quantity_raw'),'reason',json_extract(data,'$.reason')) data FROM copy_events ORDER BY detected_at DESC LIMIT 30").all().map(r=>({...r,data:JSON.parse(r.data)}));
 const config=setting('copy_config'),accounts={};
 const positions=db.prepare("SELECT id,target_id,token,mode,quantity_raw,cost_raw,opened_at,closed_at,json_object('symbol',json_extract(data,'$.symbol'),'decimals',json_extract(data,'$.decimals'),'unrealized_raw',json_extract(data,'$.unrealized_raw'),'marked_at',json_extract(data,'$.marked_at')) data FROM copy_positions WHERE closed_at IS NULL ORDER BY opened_at DESC").all();
 for(const mode of ['PAPER','PAPER_BASELINE','SHADOW','LIVE']){
  const ledger=db.prepare('SELECT delta_raw,pnl_raw,at FROM copy_ledger WHERE mode=? ORDER BY at DESC').all(mode);const held=positions.filter(p=>p.mode===mode);
  const reserve=db.prepare("SELECT reserved_raw FROM copy_actions WHERE mode IN (?,?) AND state NOT IN ('FILLED','REJECTED','CANCELLED','FAILED','SKIPPED')").all(mode==='LIVE'?'LIVE_APPROVAL':mode,mode==='LIVE'?'LIVE_AUTO':mode).reduce((s,r)=>s+BigInt(r.reserved_raw),0n);
  accounts[mode]={cash_bnb:bnb(wei(mode.startsWith('PAPER')?config.paper_capital_bnb:mode==='SHADOW'?config.shadow_capital_bnb:config.allocation_bnb)+ledger.reduce((s,l)=>s+BigInt(l.delta_raw),0n)),reserved_bnb:bnb(reserve),exposure_bnb:bnb(held.reduce((s,p)=>s+BigInt(p.cost_raw),0n)),realized_bnb:bnb(ledger.reduce((s,l)=>s+BigInt(l.pnl_raw),0n)),today_bnb:bnb(ledger.filter(l=>l.at>=Math.floor(Date.now()/86400000)*86400000).reduce((sum,l)=>sum+BigInt(l.pnl_raw),0n)),loss_streak:ledger.filter(l=>BigInt(l.pnl_raw)!==0n).findIndex(l=>BigInt(l.pnl_raw)>0n)===-1?ledger.filter(l=>BigInt(l.pnl_raw)<0n).length:ledger.filter(l=>BigInt(l.pnl_raw)!==0n).findIndex(l=>BigInt(l.pnl_raw)>0n),open:held.length};
 }
 const health=db.prepare("SELECT id,status,updated_at,json_object('error',json_extract(data,'$.error'),'head',json_extract(data,'$.head'),'latency_ms',json_extract(data,'$.latency_ms'),'ws',json_extract(data,'$.ws')) data FROM copy_provider_health").all().map(r=>({...r,data:JSON.parse(r.data)}));
 const fields={token:'e:token',target_tokens_raw:'e:quantity_raw',target_execution_price:'e:price_quote',source:'e:detection_source',target_bnb_evidence:'e:quote_evidence_method',our_copy_size_raw:'a:fill.input_raw',our_quote_price:'a:comparison.our_price_bnb',our_output_raw:'a:fill.output_raw',reaction_ms:'a:paper_reaction_ms',price_gap_pct:'a:comparison.price_gap_pct',realized_pnl_raw:'a:fill.pnl_raw',historical:'e:history'};
 const projection=Object.entries(fields).map(([name,p])=>{const [table,path]=p.split(':');return `json_extract(${table}.data,'$.${path}') ${name}`;}).join(',');
 const target_vs_copy=db.prepare(`SELECT e.hash target_tx,e.kind target_side,e.detected_at first_seen,coalesce(a.state,e.status) status,coalesce(a.error,json_extract(e.data,'$.reason')) reason,a.mode our_mode,CASE WHEN json_extract(e.data,'$.quote_token')='0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c' THEN json_extract(e.data,'$.quote_raw') END target_bnb_raw,${projection} FROM copy_events e LEFT JOIN copy_actions a ON a.event_id=e.id ORDER BY e.detected_at DESC LIMIT 30`).all();
 // Preserve the existing statistics definitions; omit raw quote/simulation payloads.
 const selectJson=(alias,paths)=>`json_object(${paths.flatMap(p=>[`'${p}'`,p==='shadow'?`json_object('status',json_extract(${alias}.data,'$.shadow.status'),'error',json_extract(${alias}.data,'$.shadow.error'),'unsigned_tx_built',json_extract(${alias}.data,'$.shadow.unsigned_tx_built'),'expected_gas_fee_raw',json_extract(${alias}.data,'$.shadow.expected_gas_fee_raw'),'simulation',json_object('status',json_extract(${alias}.data,'$.shadow.simulation.status')),'quote',json_object('amount_raw',json_extract(${alias}.data,'$.shadow.quote.amount_raw'),'min_out_raw',json_extract(${alias}.data,'$.shadow.quote.min_out_raw')))`:`json_extract(${alias}.data,'$.${p}')`]).join(',')})`;
 const profileRows=db.prepare(`SELECT ${selectJson('p',['version','history','side','token','target_hash','detection_source','pending_before_head','pending_advantage_ms','wall','stages','shadow'])} profile,${selectJson('e',['quote_token','decimals','quote_raw','quantity_raw','quote_estimate','sold_fraction'])} target,${selectJson('a',['fill','comparison'])} action,a.state,a.error,l.pnl_raw,l.fee_raw FROM copy_latency_profiles p LEFT JOIN copy_events e ON e.id=p.event_id LEFT JOIN copy_actions a ON a.event_id=p.event_id AND a.mode='PAPER' LEFT JOIN copy_ledger l ON l.action_id=a.id ORDER BY p.first_seen_at DESC LIMIT 300`).all();
 const profiles=profileRows.map(r=>{const p=JSON.parse(r.profile);return {...p,comparison:compareTrade(p,JSON.parse(r.target),JSON.parse(r.action),r)};});
 const latency_profile={...summarizeProfiles(profiles),metrics_window:'LAST_300_PROFILES',records:profiles.slice(0,30),detail_on_demand:true};
 const feed=db.prepare("SELECT id,at,kind,message,'{}' data FROM engine_events ORDER BY id DESC LIMIT 30").all().map(r=>({...r,data:{}}));
 const now=Date.now();const snapshot={dashboard_version:1,observed_at:now,feed,copy:{server_time:now,config,accounts,health,target_vs_copy,latency_profile,positions:positions.slice(0,100).map(p=>({...p,data:JSON.parse(p.data)})),runtime:{status:runtime.status,at:runtime.at,last_scanned_at:runtime.last_scanned_at,boot_at:runtime.boot_at,observed_head:runtime.observed_head,latest_scanned_block:runtime.latest_scanned_block,head_lag:runtime.head_lag,block_lag:runtime.block_lag,missing_blocks:runtime.missing_blocks},actions,events}};
 db.exec('COMMIT');parentPort.postMessage(snapshot);
 }catch(e){try{db.exec('ROLLBACK');}catch{}parentPort.postMessage({error:e.message});}}
publish();setInterval(publish,2000);
