// Virtual fills are atomic; each record retains the real quote and its research assumptions.
const engineGate=" AND (COALESCE((SELECT value FROM settings WHERE key='engine_enforced'),'false')!='true' OR (SELECT value FROM settings WHERE key='engine_desired')='\"RUNNING\"')";
export async function commitPaperBuy(store,{run,token,tradeId,quantity,price,quote,cost,now,epoch,context={}}){
 const reserve=Math.ceil(run.capital_cents*run.config.reserve_pct/100);const expectedEpoch=epoch??await store.setting('epoch');
 await store.batch([
 ["INSERT INTO positions(id,run_id,chain,mode,token_id,quantity_raw,decimals,cost_cents,entry_price,high_price,opened_at,version_id) SELECT ?,?,?,'PAPER',?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM runs WHERE id=? AND status='RUNNING' AND cash_cents>=?) AND (SELECT value FROM settings WHERE key='trading_enabled')='true' AND COALESCE((SELECT value FROM settings WHERE key='entries_paused'),'false')!='true' AND CAST((SELECT value FROM settings WHERE key='epoch') AS INTEGER)=? AND NOT EXISTS(SELECT 1 FROM positions WHERE run_id=? AND token_id=? AND closed_at IS NULL) AND (SELECT COUNT(*) FROM positions WHERE run_id=? AND closed_at IS NULL)<? AND (SELECT COALESCE(SUM(realized_cents),0) FROM positions WHERE run_id=? AND closed_at>=?)>?"+engineGate,[tradeId,run.id,token.chain??token.id.split(':')[0],token.id,quantity,token.decimals,cost,price,price,now,run.version_id,run.id,cost+reserve,expectedEpoch,run.id,token.id,run.id,run.config.max_positions??20,run.id,Math.floor(now/86400000)*86400000,-(run.config.daily_loss_cents??Number.MAX_SAFE_INTEGER)]],
 ['UPDATE runs SET cash_cents=cash_cents-? WHERE id=? AND EXISTS(SELECT 1 FROM positions WHERE id=?) AND NOT EXISTS(SELECT 1 FROM orders WHERE id=?)',[cost,run.id,tradeId,tradeId]],
 ["INSERT INTO orders(id,idempotency_key,run_id,chain,mode,side,token_id,version_id,state,input_mint,output_mint,amount_raw,notional_cents,epoch,policy_revision,created_at,updated_at,quote) SELECT ?,?,?,?,'PAPER','BUY',?,?,'PAPER_FILLED',?,?,?,?,?,0,?,?,? WHERE EXISTS(SELECT 1 FROM positions WHERE id=?)",[tradeId,tradeId,run.id,token.chain??token.id.split(':')[0],token.id,run.version_id,quote.inputMint,token.address,quote.inAmount,cost,expectedEpoch,now,now,JSON.stringify(quote),tradeId]],
 ['INSERT OR IGNORE INTO order_context SELECT ?,?,?,?,?,?,?,NULL WHERE EXISTS(SELECT 1 FROM orders WHERE id=?)',[tradeId,context.signal_id??null,context.score??null,context.reason??'STRATEGY_SIGNAL',price,context.market_cap??null,quote.slippageBps??null,tradeId]]
 ]);return !!await store.get('SELECT id FROM orders WHERE id=?',tradeId);
}
export async function commitPaperSell(store,{run,position,token,tradeId,proceeds,quote,now,epoch,context={}}){
 const pnl=proceeds-position.cost_cents,expectedEpoch=epoch??await store.setting('epoch');
 await store.batch([
 ["INSERT INTO orders(id,idempotency_key,run_id,chain,mode,side,token_id,version_id,state,input_mint,output_mint,amount_raw,notional_cents,epoch,policy_revision,created_at,updated_at,quote) SELECT ?,?,?,?,'PAPER','SELL',?,?,'PAPER_FILLED',?,?,?,?,?,0,?,?,? WHERE EXISTS(SELECT 1 FROM positions WHERE id=? AND closed_at IS NULL) AND EXISTS(SELECT 1 FROM runs WHERE id=? AND status IN ('RUNNING','LOSS_LIMIT')) AND (SELECT value FROM settings WHERE key='trading_enabled')='true' AND CAST((SELECT value FROM settings WHERE key='epoch') AS INTEGER)=?"+engineGate,[tradeId,tradeId,run.id,token.chain??token.id.split(':')[0],token.id,position.version_id??run.version_id,token.address,quote.outputMint,position.quantity_raw,proceeds,expectedEpoch,now,now,JSON.stringify(quote),position.id,run.id,expectedEpoch]],
 ['UPDATE runs SET cash_cents=cash_cents+? WHERE id=? AND EXISTS(SELECT 1 FROM orders WHERE id=?) AND EXISTS(SELECT 1 FROM positions WHERE id=? AND closed_at IS NULL)',[proceeds,run.id,tradeId,position.id]],
 ['UPDATE positions SET closed_at=?,realized_cents=? WHERE id=? AND closed_at IS NULL AND EXISTS(SELECT 1 FROM orders WHERE id=?)',[now,pnl,position.id,tradeId]],
 ['INSERT OR IGNORE INTO order_context SELECT ?,NULL,NULL,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM orders WHERE id=?)',[tradeId,context.reason??'EXIT',context.price??null,context.market_cap??null,quote.slippageBps??null,pnl,tradeId]]
 ]);return !!await store.get('SELECT id FROM orders WHERE id=?',tradeId);
}
