import {decrypt} from './util.mjs';
import {schema,defaults,initialChains} from './schema.mjs';
import {engineSchema,engineDefaults,emit} from './engine-state.mjs';
import {copySchema,copyDefaults,targetDefaults,TARGET} from './copy/schema.mjs';
export class Store {
 constructor(driver,options={}){this.driver=driver;this.options=options;}
 async all(sql,...args){const rows=await this.driver.all(sql,args);for(const r of rows)for(const field of ['rpc_url','ws_url'])if(r[field]?.startsWith('enc:'))r[field]=await decrypt(r[field].slice(4),this.options.encryptionKey);return rows;}
 async get(sql,...args){return (await this.all(sql,...args))[0]??null;}
 async run(sql,...args){return this.driver.run(sql,args);}
 async batch(statements){return this.driver.batch(statements);}
 async init(){await this.driver.exec(schema+engineSchema+copySchema);for(const [key,value] of Object.entries({...defaults,...engineDefaults,...copyDefaults}))await this.run('INSERT OR IGNORE INTO settings VALUES (?,?,?)',key,JSON.stringify(value),Date.now());for(const c of initialChains)await this.run('INSERT OR IGNORE INTO chains VALUES (?,?,?,?,?,?)',...c);await this.run('INSERT OR IGNORE INTO watched_wallets(wallet_id) SELECT id FROM wallets');await this.run('INSERT OR IGNORE INTO copy_targets VALUES (?,?,?,?,?,?)',TARGET,TARGET,'Narrativas BNB',1,JSON.stringify(targetDefaults),Date.now());}
 async setting(key){const v=await this.get('SELECT value FROM settings WHERE key=?',key);return v?JSON.parse(v.value):null;}
 async set(key,value){await this.run('INSERT INTO settings VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at',key,JSON.stringify(value),Date.now());}
 async log(category,event,detail={},entity=null,level='INFO'){await this.run('INSERT INTO audit_log(created_at,level,category,event,entity_id,detail) VALUES (?,?,?,?,?,?)',Date.now(),level,category,event,entity,JSON.stringify(detail));}
 async transition(id,from,to,fields={}){const allowed=['quote','build','simulation','tx_digest','expires_at','signature','signed_payload','error','approved_at'];for(const k of Object.keys(fields))if(!allowed.includes(k))throw Error('Invalid order field');const r=await this.run(`UPDATE orders SET state=?,updated_at=?${Object.keys(fields).map(k=>`,${k}=?`).join('')} WHERE id=? AND state=?`,to,Date.now(),...Object.values(fields),id,from);if(r.changes!==1)throw Error('ORDER_STATE_CONFLICT');await this.log('EXECUTION',to,{},id);await emit(this,'ORDER',to,{order_id:id},null,id);}
 async stop(){const now=Date.now();await this.batch([["UPDATE settings SET value=json_set(value,'$.enabled',json('false'),'$.paused',json('true'),'$.live_enabled',json('false'),'$.auto_armed',json('false'),'$.epoch',json_extract(value,'$.epoch')+1),updated_at=? WHERE key='copy_config'",[now]],["UPDATE copy_actions SET state='CANCELLED',reserved_raw='0',error='EMERGENCY_STOP',updated_at=? WHERE state IN ('DETECTED','PROCESSING','QUOTED','AWAITING_APPROVAL','APPROVED','SIGNED')",[now]],['UPDATE settings SET value=\'false\',updated_at=? WHERE key=\'trading_enabled\'',[now]],['UPDATE settings SET value=CAST(CAST(value AS INTEGER)+1 AS TEXT),updated_at=? WHERE key=\'epoch\'',[now]],['UPDATE settings SET value=\'"STOPPED"\',updated_at=? WHERE key=\'mode\'',[now]],["UPDATE orders SET state='CANCELLED',updated_at=? WHERE state IN ('CREATED','QUOTED','BUILT','SIMULATED','AWAITING_APPROVAL','APPROVED','RESERVED','SIGNED')",[now]],["UPDATE reservations SET status='RELEASED' WHERE order_id IN (SELECT id FROM orders WHERE state='CANCELLED')",[]],["UPDATE runs SET status='STOPPED',stopped_at=? WHERE status='RUNNING'",[now]]]);await this.log('RISK','EMERGENCY_STOP',{monitoring_continues:true});}
}
export function d1Driver(db){return {all:async(sql,args)=>(await db.prepare(sql).bind(...args).all()).results,run:async(sql,args)=>{const r=await db.prepare(sql).bind(...args).run();return {changes:r.meta.changes};},exec:async(sql)=>{for(const q of sql.split(';').map(x=>x.trim()).filter(Boolean))await db.prepare(q).run();},batch:async(stmts)=>db.batch(stmts.map(([s,a])=>db.prepare(s).bind(...a)))};}
