'use client';
import React,{useEffect,useState} from 'react';
import {Play,Pause,Square,Activity,ArrowUpRight,AlertTriangle,Wallet,Radio,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {providerErrorMessage} from '../core/provider-status.mjs';
type Obj=Record<string,any>;
const usd=(c:any)=>c===null||c===undefined?'—':new Intl.NumberFormat('es-AR',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(c/100);
const value=(n:any)=>n===null||n===undefined?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:6,notation:Math.abs(n)>1e6?'compact':'standard'}).format(n);
const time=(t:number)=>t?new Date(t).toLocaleTimeString([],{hour12:false}):'—';
const explorer=(chain:string,hash:string)=>(chain?.startsWith('solana')?'https://solscan.io/tx/':'https://robinhoodchain.blockscout.com/tx/')+hash;
const short=(s:string)=>s?s.slice(0,6)+'…'+s.slice(-5):'—';
const duration=(n:number)=>{const s=Math.max(0,Math.floor(n/1000));return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(v=>String(v).padStart(2,'0')).join(':');};
function Box({title,action,children}:{title:string,action?:React.ReactNode,children:React.ReactNode}){return <section className="panel"><div className="panel-head"><h2>{title}</h2>{action}</div>{children}</section>;}
function Empty({children}:{children:React.ReactNode}){return <p className="p-6 muted text-sm leading-6">{children}</p>;}
function Status({label,status}:{label:string,status:string}){return <div className="engine-status"><span>{label}</span><strong className={['RUNNING','CONNECTED','PAPER'].includes(status)?'good':['ERROR','OFFLINE','NOT_PROVISIONED','DEGRADED'].includes(status)?'bad':''}>{status.replaceAll('_',' ')}</strong></div>;}
export default function LiveDashboard({data,busy,connection,act,navigate,configure,inspect}:{data:Obj|null,busy:string,connection:string,act:(path:string,body?:Obj,label?:string)=>Promise<any>,navigate:(page:string)=>void,configure:(kind:string)=>void,inspect:(path:string)=>void}){
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 const engine=data?.engine??{},settings=data?.settings??{},mode=settings.mode??'OBSERVE',run=data?.runs?.find((r:Obj)=>r.status==='RUNNING')??data?.runs?.[0];
 const positions=(data?.positions??[]).filter((p:Obj)=>!p.closed_at),trades=data?.orders??[],events=data?.feed??[],networks=engine.networks??[];
 const prices=data?.tokens??[],decisions=data?.decisions??[],walletEvents=events.filter((e:Obj)=>['WALLET','WALLET_TX','LEARNING'].includes(e.kind));
 const lastTick=settings.scanner_last_tick,unrealized=positions.filter((p:Obj)=>p.mode==='PAPER').reduce((a:number,p:Obj)=>a+(p.unrealized_cents??0),0),stalePositions=positions.some((p:Obj)=>p.mode==='PAPER'&&p.unrealized_cents===null);
 const activeStrategy=data?.strategies?.find((s:Obj)=>s.id===(mode==='PAPER'?run?.version_id:settings.automation?.version_id));
 const networkStatus=(id:string)=>{const ws=networks.find((n:Obj)=>n.chain===id),rpc=data?.providers?.find((p:Obj)=>p.id===id);return ws?.status==='CONNECTED'&&now-ws.last_event<45000?'CONNECTED':rpc?.status==='CONNECTED'&&now-rpc.last_success<60000?'RPC ONLY':rpc?.status??'NOT TESTED';};
 return <div className="stack live-terminal">
  <section className="engine-command panel">
   <div className="engine-overline"><span className="eyebrow">LIVE ENGINE</span><span className="muted text-sm">Panel: {connection==='CONNECTED'?'conectado':'reconectando'}</span></div>
   <div className="engine-status-row"><Status label="ENGINE" status={engine.state??'CONNECTING'}/><Status label="MODE" status={mode}/><Status label="SOLANA" status={networkStatus('solana')}/><Status label="ROBINHOOD" status={networkStatus('robinhood')}/><Status label="MERCADO" status={data?.providers?.find((p:Obj)=>p.id==='market')?.status??'NOT TESTED'}/><div className="engine-status"><span>UPTIME</span><strong className="mono">{engine.started_at&&engine.state==='RUNNING'?duration(now-engine.started_at):'—'}</strong></div></div>
   <div className="engine-actions"><Button disabled={!!busy||engine.desired==='RUNNING'} onClick={()=>engine.available?act('engine/start',{},'Iniciar motor'):navigate('Settings')}><Play size={16}/>START ENGINE</Button><Button variant="outline" disabled={!!busy||!engine.available} onClick={()=>act(engine.entries_paused?'engine/resume':'engine/pause',{},engine.entries_paused?'Reanudar entradas':'Pausar entradas')}><Pause size={16}/>{engine.entries_paused?'RESUME ENTRIES':'PAUSE NEW ENTRIES'}</Button><Button variant="outline" disabled={!!busy||!engine.available||engine.desired==='STOPPED'} onClick={()=>act('engine/stop',{},'Detener motor')}><Square size={15}/>STOP ENGINE</Button><Button variant="outline" onClick={()=>navigate('Run Bot')}><Settings2 size={15}/>Modo y capital</Button></div>
   <div className="engine-caption"><span>Estrategia: <strong>{activeStrategy?activeStrategy.name+' · v'+activeStrategy.version:'Sin seleccionar'}</strong></span><span>{engine.entries_paused?'Entradas pausadas; las salidas siguen activas si el motor está funcionando.':mode==='OBSERVE'?'Observación: sin operaciones.':mode==='PAPER'?'Mercado real · capital virtual':mode==='LIVE_APPROVAL'?'Cada envío requiere aprobación y firma':'Preparación y simulación'}</span></div>
  </section>
  {!engine.available&&<div className="notice engine-setup"><AlertTriangle size={20}/><div><strong>Falta conectar tu servidor persistente.</strong><p>Esta URL guarda tu investigación. Para trabajar con Chrome cerrado, instalá el motor en tu PC o VPS. El nuevo servicio incluye esta misma interfaz, API, WebSockets y base persistente.</p><Button className="mt-3" variant="outline" onClick={()=>navigate('Settings')}>Instalar y conectar el motor <ArrowUpRight size={15}/></Button></div></div>}
  {engine.available&&engine.state==='STOPPED'&&<div className="notice">El motor está detenido. START ENGINE comienza a monitorear. Para PAPER, elegí una sesión desde “Modo y capital”.</div>}
  {engine.available&&engine.state==='OFFLINE'&&<div className="notice error">El proceso no envía heartbeat. El supervisor intentará recuperarlo. No se muestra como funcionando.</div>}
  <div className="live-stats">{[
   ['Balance PAPER',run?usd(run.cash_cents):'—','Capital virtual disponible'],
   ['PnL hoy · realizado',usd(mode.startsWith('LIVE')?data?.metrics?.live_today_pnl:data?.metrics?.paper_today_pnl),'Desde 00:00 UTC'],
   ['Posiciones abiertas',positions.length,stalePositions?'PnL flotante: faltan precios recientes':'Flotante PAPER: '+usd(unrealized)],
   ['Operaciones',engine.counts?.trades??0,'PAPER_FILLED / RECONCILED'],
   ['Win rate PAPER',data?.metrics?.paper_closed?value(data.metrics.paper_wins/data.metrics.paper_closed*100)+'%':'—','Solo posiciones cerradas'],
   ['Tokens observados',engine.counts?.tokens??0,(engine.counts?.tokens_min??0)+' nuevos en el último minuto']
  ].map(([label,note,detail])=><div className="panel stat" key={String(label)}><div className="eyebrow">{label}</div><div className="number mono">{note}</div><small>{detail}</small></div>)}</div>
  <div className="engine-summary-strip"><span>Pools observadas: <b>{engine.counts?.pools??0}</b></span><span>Eventos de wallets: <b>{engine.counts?.wallet_events??0}</b></span><span>Señales: <b>{engine.counts?.signals??0}</b></span><span>Último ciclo: <b>{lastTick?time(lastTick.at):'sin ejecutar'}</b></span><span>{lastTick?`${lastTick.tokens_processed} tokens · ${lastTick.signals} señales · ${lastTick.rejected??0} rechazos`:''}</span></div>
  <div className="live-columns">
   <Box title="Live Market Feed" action={<Button size="sm" variant="ghost" onClick={()=>navigate('Live Scanner')}>Ver mercado <ArrowUpRight size={14}/></Button>}><div className="live-table-scroll"><Table><TableHeader><TableRow>{['Token / red','Precio USD','Liquidez','Vol. 5m','Buys / sells','Actualización'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{prices.slice(0,12).map((t:Obj)=><TableRow className="cursor-pointer" key={t.id} onClick={()=>inspect('tokens/'+encodeURIComponent(t.id))}><TableCell><strong>{t.symbol??short(t.address)}</strong><div className="muted text-xs">{t.chain} · {short(t.address)}</div></TableCell><TableCell className="mono">{value(t.price)}</TableCell><TableCell>{value(t.liquidity)}</TableCell><TableCell>{value(t.volume_5m)}</TableCell><TableCell>{t.buys_5m??'—'} / {t.sells_5m??'—'}</TableCell><TableCell className={now-t.received_at>45000?'bad':'muted'}>{t.received_at?Math.floor((now-t.received_at)/1000)+'s':'sin precio'}</TableCell></TableRow>)}</TableBody></Table></div>{!prices.length&&<Empty>Los tokens aparecerán cuando el motor reciba eventos o los encuentre en los proveedores. No hay registros de ejemplo.</Empty>}<p className="p-4 muted text-xs border-t">Precios, volumen y liquidez: DexScreener REST, con hora de recepción. Eventos de pools: WebSocket y verificación RPC cuando la red está conectada.</p></Box>
   <Box title="Bot Decisions" action={<span className="pill">{decisions.length} recientes</span>}><div className="decision-scroll">{decisions.slice(0,15).map((d:Obj)=><div className="decision-item" key={d.id}><div className="flex justify-between gap-3"><strong>{d.symbol??short(d.token_id?.split(':')[1])}</strong><span className={d.decision==='SIGNAL'?'good':'muted'}>{d.decision} · {d.score}</span></div><div className="muted text-xs mt-1">{time(d.observed_at)} · {d.strategy} v{d.version}</div><div className="text-sm mt-2">{d.reasons.filter((r:Obj)=>r.status!=='PASS').map((r:Obj)=>`${r.name}: ${r.value===null?'sin dato':value(r.value)} (requiere ${r.threshold})`).join(' · ')||'Cumple las reglas de entrada; pasa a evaluación de ejecución.'}</div></div>)}</div>{!decisions.length&&<Empty>Acá vas a ver qué token evaluó, su score y por qué lo aceptó o rechazó. Iniciá el motor y seleccioná una estrategia.</Empty>}</Box>
  </div>
  <Box title="Open Positions · posiciones abiertas" action={<Button variant="ghost" size="sm" onClick={()=>navigate('Positions')}>Ver todas</Button>}><div className="live-table-scroll"><Table><TableHeader><TableRow>{['Token','Modo','Invertido','Precio actual','PnL flotante','Abierta'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{positions.map((p:Obj)=><TableRow key={p.id}><TableCell>{p.symbol??short(p.token_id)}</TableCell><TableCell>{p.mode}</TableCell><TableCell>{usd(p.cost_cents)}</TableCell><TableCell>{value(p.current_price)}</TableCell><TableCell className={p.unrealized_cents>=0?'good':'bad'}>{usd(p.unrealized_cents)}</TableCell><TableCell>{time(p.opened_at)}</TableCell></TableRow>)}</TableBody></Table></div>{!positions.length&&<Empty>Todavía no abrió posiciones. Mirá “Bot Decisions” para conocer las condiciones rechazadas. No necesita comprar en cada ciclo.</Empty>}</Box>
  <Box title="Live Trades · operaciones" action={<Button variant="ghost" size="sm" onClick={()=>navigate('History')}>Historial completo</Button>}><div className="live-table-scroll"><Table><TableHeader><TableRow>{['Hora / red','Token','BUY / SELL','Estrategia','Monto','Precio','MC','Slippage','Score / motivo','Estado'].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{trades.slice(0,20).map((t:Obj)=><TableRow className="cursor-pointer" key={t.id} onClick={()=>inspect('orders/'+t.id)}><TableCell>{time(t.created_at)}<div className="muted text-xs">{t.chain} · {t.mode}</div></TableCell><TableCell>{t.symbol??short(t.token_id?.split(':')[1])}</TableCell><TableCell className={t.side==='BUY'?'good':'muted'}>{t.side}</TableCell><TableCell>{t.strategy??'—'} {t.version?'v'+t.version:''}</TableCell><TableCell>{usd(t.notional_cents)}{t.realized_cents!==null&&<div className={t.realized_cents>=0?'good':'bad'}>{usd(t.realized_cents)}</div>}</TableCell><TableCell>{value(t.price)}</TableCell><TableCell>{value(t.market_cap)}</TableCell><TableCell>{t.slippage_bps!==null?t.slippage_bps/100+'%':'—'}</TableCell><TableCell>{t.score??'—'}<div className="text-xs muted">{t.reason??t.error??''}</div></TableCell><TableCell><span className="pill">{t.state}</span></TableCell></TableRow>)}</TableBody></Table></div>{!trades.length&&<Empty>0 operaciones registradas. Cuando se ejecute una compra o venta virtual aparecerá automáticamente acá, junto con su motivo y cotización.</Empty>}</Box>
  <div className="live-columns"><Box title="Watched Trader Activity" action={<Button variant="ghost" size="sm" onClick={()=>navigate('Traders')}>Agregar trader</Button>}><div className="decision-scroll">{walletEvents.slice(0,12).map((e:Obj)=><div className="decision-item" key={e.id}><div className="muted text-xs">{time(e.at)} · {e.chain}</div><strong>{e.message}</strong><p className="text-sm muted break-words">{e.data.hash?short(e.data.hash):''} {e.data.token_address?'· '+short(e.data.token_address):''}</p>{e.data.context_timing&&<p className="text-xs muted">Contexto: {e.data.context_timing} · MC {value(e.data.market_cap)} · Liquidez {value(e.data.liquidity)}</p>}{e.data.hash&&<a className="text-xs good" title={e.data.hash} href={explorer(e.chain,e.data.hash)} target="_blank" rel="noreferrer">Ver transacción ↗</a>}</div>)}</div>{!walletEvents.length&&<Empty>Agregá una wallet en Traders. El motor vigila su actividad nueva y recupera páginas pendientes. Los movimientos interpretados se identifican como inferencias.</Empty>}</Box>
  <Box title="System Health"><div className="p-5">{networks.map((n:Obj)=><div className="health-item" key={n.chain}><div className="flex justify-between"><strong>{n.chain}</strong><span className={n.status==='CONNECTED'?'good':'bad'}>{n.status}</span></div><p className="muted text-sm">{n.provider} · WS · bloque/slot {n.last_block??'—'}</p><p className="muted text-xs">Último evento {time(n.last_event)} · {n.subscription_count} suscripciones · {n.reconnects} reconexiones</p>{n.error&&<p className="bad text-sm break-words">{n.error}</p>}</div>)}{(data?.providers??[]).map((p:Obj)=><div className="health-item text-sm" key={'rpc-'+p.id}><strong>{p.id} · {p.status}</strong><p className="muted">RPC / API · {p.latency_ms??'—'} ms · último éxito {time(p.last_success)} · bloque {p.block??'—'}</p>{p.error&&<p className="bad">{providerErrorMessage(p.error)}</p>}</div>)}<div className="health-item text-sm">Cola: {(engine.jobs??[]).map((j:Obj)=>j.state+' '+j.count).join(' · ')||'vacía'}</div><div className="text-sm muted mt-3">Heartbeat: {time(engine.heartbeat?.at)}<br/>Último trabajo terminado: {time(engine.heartbeat?.last_completed_at)}<br/>Duración del ciclo: {lastTick?value(lastTick.duration_ms/1000)+'s':'—'}</div>{engine.heartbeat?.last_error&&<p className="bad text-sm mt-3 break-words">{providerErrorMessage(engine.heartbeat.last_error)}</p>}</div></Box></div>
  <Box title="Actividad del motor"><Tabs defaultValue="all"><TabsList className="m-4"><TabsTrigger value="all">Todo</TabsTrigger><TabsTrigger value="errors">Errores</TabsTrigger><TabsTrigger value="pools">Pools</TabsTrigger></TabsList>{['all','errors','pools'].map(tab=><TabsContent key={tab} value={tab}><div className="engine-feed">{events.filter((e:Obj)=>tab==='all'||tab==='errors'&&['ERROR','RISK'].includes(e.kind)||tab==='pools'&&e.kind==='POOL').slice(0,60).map((e:Obj)=><div className="engine-feed-row" key={e.id}><span className="mono muted">{time(e.at)}</span><span className={e.kind==='ERROR'?'bad':e.kind==='TRADE'?'good':'muted'}>{e.kind}</span><span>{e.message}{e.data.error&&<span className="bad"> · {providerErrorMessage(e.data.error)}</span>}{e.data.hash&&<a className="good mono" title={e.data.hash} href={explorer(e.chain,e.data.hash)} target="_blank" rel="noreferrer"> · {short(e.data.hash)} ↗</a>}</span></div>)}</div>{!events.length&&<Empty>El motor todavía no generó eventos. Los registros muestran únicamente actividad persistida.</Empty>}</TabsContent>)}</Tabs></Box>
 </div>;
}
