'use client';
import React from 'react';
import {Button} from '@/components/ui/button';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {FlaskConical,Play,Pause,Users,Download} from 'lucide-react';
type Obj=Record<string,any>;
const cash=(v:any)=>Number.isFinite(v)?new Intl.NumberFormat('es-AR',{style:'currency',currency:'USD'}).format(v/100):'Sin resultado';
const pct=(v:any)=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'—';
const labels:Obj={COLLECTING:'RECOLECTANDO DATOS',TRAINING:'ENTRENANDO',PAPER_ELIGIBLE:'LISTA PARA PROBAR EN PAPER',REJECTED:'NO SUPERÓ LA VALIDACIÓN',ERROR:'ERROR',PAUSED:'PAUSADO'};
const reasons:Obj={INSUFFICIENT_WALLET_TRAIN:'Faltan compras verificadas de las wallets en el periodo de entrenamiento.',INSUFFICIENT_SPLITS:'Faltan tokens distintos en los tres periodos.',OBSERVATION_SPAN:'El dataset todavía no cubre 24 horas.',NO_CANDIDATE_WITH_COVERAGE:'Ninguna regla tuvo suficientes operaciones con precios completos.'};
const checks:Obj={test_sample:'Al menos 10 operaciones en prueba final',independent_market_entries:'Al menos 10 entradas sin señal del trader',complete_prices:'Precios completos, incluida la estrategia de referencia',positive_validation:'Resultado positivo después de costes en validación',positive_test:'Resultado positivo después de costes en prueba final',better_than_baseline:'Supera la regla de referencia',drawdown:'Caída de resultados cerrados dentro del límite',observation_span:'Al menos 24 horas observadas'};
function Stage({name,result}:{name:string,result?:Obj}){return <div className="panel p-5"><div className="eyebrow">{name}</div><div className={(result?.pnl_cents>=0?'good ':'bad ')+'text-xl mono mt-3'}>{cash(result?.pnl_cents)}</div><p className="text-sm muted mt-2">{result?.trades??0} operaciones · {pct(result?.win_rate)} aciertos</p><p className="text-sm muted">Sin precio de salida: {result?.unpriced??0}</p></div>;}
export default function Training({data,busy,act,navigate}:{data:Obj|null,busy:string,act:(path:string,body?:Obj,label?:string)=>Promise<any>,navigate:(page:string)=>void}) {
 const t=data?.training;if(!t)return <div className="notice">Cargando el estado del entrenamiento…</div>;
 const enabled=t.config?.enabled,engine=data?.engine?.state==='RUNNING',state=!enabled?'PAUSED':t.status?.status??'COLLECTING';
 const count=(s:string)=>t.counts.filter((r:Obj)=>r.state===s).reduce((n:number,r:Obj)=>n+r.count,0);
 const latest=t.runs[0],wallets=t.wallets.filter((w:Obj)=>w.enabled&&w.chain==='solana');
 const exportRun=async(id:string)=>{const r=await fetch('/api/lab/training/runs/'+id);if(!r.ok)return;const d=await r.json();const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='meme-lab-training-'+id+'.json';a.click();URL.revokeObjectURL(url);};
 return <div className="stack">
  <section className="panel p-6 border-t-2 border-primary"><div className="toolbar"><div><div className="eyebrow">ENTRENAMIENTO CONTINUO · SOLANA</div><h2 className="text-xl mt-3">{labels[state]??state}</h2><p className="muted text-sm mt-2">{!engine?'Iniciá el entrenamiento para encender el motor y recopilar datos.':wallets.length?'El servidor observa tus wallets y el mercado, guarda resultados y ajusta reglas.':'Agregá una wallet Solana para comenzar.'}</p></div><span className="pill text-sm">DINERO REAL DESACTIVADO PARA ESTRATEGIAS APRENDIDAS</span></div>
   <div className="flex flex-wrap gap-3 mt-5"><Button disabled={!!busy||(enabled&&engine)} onClick={()=>act('training/start',{},'Iniciar entrenamiento')}><Play size={16}/>{enabled&&engine?'Entrenamiento activo':'INICIAR ENTRENAMIENTO'}</Button><Button variant="outline" disabled={!!busy||!enabled} onClick={()=>act('training/pause',{},'Pausar entrenamiento')}><Pause size={16}/>Pausar entrenamiento</Button><Button variant="outline" onClick={()=>navigate('Traders')}><Users size={16}/>Agregar wallets</Button></div>
   <p className="text-sm muted mt-4">El entrenamiento no abre operaciones. Cada versión necesita una prueba PAPER posterior. Cerrar Chrome no detiene el proceso del servidor.</p>
  </section>
  {(t.status?.error||t.market_error)&&<div className="notice error">{t.status?.error??t.market_error.message}. El dataset conserva los huecos de precios; no los cuenta como ganancias.</div>}
  <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{[['Wallets Solana vigiladas',wallets.length],['Tokens en seguimiento',count('CAPTURING')],['Trayectorias completas',count('READY')],['Incompletas / sin precio',count('EXCLUDED')]].map(([title,n])=><div key={String(title)} className="panel p-5"><div className="eyebrow">{title}</div><div className="text-2xl mono mt-3">{n}</div></div>)}</div>
  <section className="panel p-6"><h2 className="text-lg">¿Cuánto falta?</h2><p className="mt-3"><strong>{t.ready}</strong> / {t.required} tokens observados para el próximo intento.</p><progress className="w-full mt-3 accent-lime-400" aria-label="Tokens del siguiente dataset" value={Math.min(t.ready,t.required)} max={t.required}/><p className="text-sm muted mt-3">También hacen falta {t.required_wallet_train} compras verificadas en el periodo inicial, 24 horas de observaciones y suficientes operaciones en los periodos separados. Alcanzar el contador no garantiza aprobar.</p>{t.status?.reason&&<p className="text-sm mt-3">{reasons[t.status.reason]??t.status.reason}</p>}
   <p className="text-sm muted mt-3">Cobertura de wallets en esta versión: compras directas de PumpSwap identificadas en transacciones exitosas. Las otras rutas y las transacciones fallidas siguen registradas, pero no se usan como compras para entrenar. El contexto comienza cuando nuestro motor lo observa; no reconstruye precios históricos ausentes.</p>
  </section>
  <section className="panel"><div className="panel-head"><h2>Wallets y datos aprovechables</h2></div><Table><TableHeader><TableRow>{['Wallet','Red','Transacciones','Fallidas','Tokens para entrenar','Estado'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{t.wallets.map((w:Obj)=><TableRow key={w.id}><TableCell>{w.label||w.address.slice(0,8)}</TableCell><TableCell>{w.chain}</TableCell><TableCell>{w.transactions}</TableCell><TableCell>{w.failed}</TableCell><TableCell>{w.samples}</TableCell><TableCell>{w.chain!=='solana'?'Sin adaptador de entrenamiento':w.error?<span className="bad">{w.error}</span>:w.enabled?'Vigilando':'Pausada'}</TableCell></TableRow>)}{!t.wallets.length&&<TableRow><TableCell colSpan={6} className="py-8 text-center"><Button onClick={()=>navigate('Traders')}>Agregar la primera wallet</Button></TableCell></TableRow>}</TableBody></Table></section>
  {latest?<section className="stack"><div className="toolbar"><div><h2 className="text-xl">Última estrategia entrenada</h2><p className="muted text-sm">{new Date(latest.created_at).toLocaleString()} · {latest.result.candidate_count??0} candidatas evaluadas</p></div><Button variant="outline" onClick={()=>exportRun(latest.id)}><Download size={16}/>Exportar evidencia</Button></div>
    <div className="grid md:grid-cols-3 gap-4"><Stage name="1 · ENTRENAMIENTO" result={latest.result.train}/><Stage name="2 · VALIDACIÓN" result={latest.result.validation}/><Stage name="3 · PRUEBA FINAL" result={latest.result.test}/></div>
    <section className="panel p-6"><h3>{labels[latest.status]??latest.status}</h3>{latest.result.reason&&<p className="mt-3 text-sm">{reasons[latest.result.reason]??latest.result.reason}</p>}<div className="grid lg:grid-cols-2 gap-3 mt-4">{Object.entries(latest.result.checks??{}).map(([k,v])=><div key={k} className="flex justify-between gap-3 text-sm"><span>{checks[k]??k}</span><strong className={v?'good':'bad'}>{v?'PASA':'NO PASA'}</strong></div>)}</div><p className="text-sm muted mt-4">Costes por lado: {t.protocol.fee_bps/100}% de comisión asumida + {t.protocol.slippage_bps/100}% de slippage, impacto por liquidez y US${(t.protocol.network_fee_cents/100).toFixed(2)} de red. Precios posteriores a la señal; hipótesis de latencia: {t.protocol.latency_ms} ms. Son estimaciones históricas.</p>
      <div className="mt-5"><Button disabled={!!busy||latest.status!=='PAPER_ELIGIBLE'||!!latest.paper_run_id} onClick={()=>act('training/paper',{id:latest.id},'Iniciar US$100 virtuales')}><FlaskConical size={16}/>{latest.paper_run_id?'Prueba PAPER creada':'Probar con US$100 virtuales'}</Button></div>
      <p className="text-sm muted mt-3">Una oportunidad por token y versión, en la primera observación completa. Las reglas aprendidas aparecen también en Strategy Lab.</p>
    </section>
    {latest.paper&&<section className="panel p-6"><h3>Prueba PAPER con datos nuevos</h3><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mt-4">{[['PnL cerrado',cash(latest.paper.pnl_cents)],['Operaciones cerradas',latest.paper.trades+' / 50'],['Tokens distintos',latest.paper.distinct_tokens+' / 30'],['Días con evidencia',latest.paper.days.toFixed(1)+' / 7']].map(([k,v])=><div key={k}><div className="eyebrow">{k}</div><div className="text-xl mt-2">{v}</div></div>)}</div><p className="mt-4">{latest.paper.review_ready?'Cumple los filtros de PAPER: revisar resultados y ejecución antes de decidir sobre dinero real.':'La prueba futura todavía no reúne los requisitos para revisión.'}</p><Button className="mt-4" variant="outline" onClick={()=>navigate('Dashboard')}>Ver operaciones y posiciones</Button></section>}
    <details className="panel p-5"><summary className="cursor-pointer">Versiones anteriores y trazabilidad</summary><p className="mono text-xs break-all mt-3">Dataset: {latest.result.dataset_digest}</p><p className="text-sm muted mt-3">La caída calculada usa resultados cerrados y puede subestimar pérdidas temporales. La evidencia exportada contiene parámetros, transacciones fuente, precios, divisiones temporales y resultados. Cada prueba final se usa una sola vez.</p>{t.runs.slice(1).map((r:Obj)=><div key={r.id} className="metric-row"><span>{new Date(r.created_at).toLocaleString()} · {labels[r.status]??r.status}</span><Button size="sm" variant="outline" onClick={()=>exportRun(r.id)}>Evidencia</Button></div>)}</details>
   </section>:<section className="panel p-6"><h2>Todavía no hay una estrategia entrenada</h2><p className="text-sm muted mt-3">Se ajustarán reglas con el primer periodo, se elegirá una candidata con el segundo y se evaluará una sola vez en el tercero. Los tokens sin salida observable permanecen en el dataset.</p></section>}
 </div>;
}
