import {latencyProfileSummary} from './latency-profile.mjs';
import {decode,quantiles} from './common.mjs';
export const COPY_LATENCY_KINDS=['MEMPOOL_DETECTION_MS','BLOCK_DETECTION_MS','DECODE_MS','QUOTE_MS','PAPER_REACTION_MS','TOTAL_COPY_REACTION_MS'];
export async function copyAuditSummary(store){
 const latencies={};for(const kind of COPY_LATENCY_KINDS){const rows=await store.all("SELECT duration_ms FROM copy_samples WHERE kind=? AND json_extract(data,'$.historical') IS NOT 1 ORDER BY at DESC LIMIT 300",kind);latencies[kind]=quantiles(rows.map(r=>r.duration_ms));}
 const sources=(await store.all('SELECT * FROM copy_source_transactions ORDER BY first_seen_at DESC LIMIT 100')).map(r=>{const d=decode(r.data);return {chain_id:r.chain_id,hash:r.hash,status:r.status,first_seen_at:r.first_seen_at,source:d.source,from:d.tx?.from,nonce:d.tx?.nonce,block:d.tx?.blockNumber};});
 const rows=await store.all("SELECT e.hash,e.kind,e.detected_at,e.status target_status,e.data target_data,a.id action_id,a.mode,a.state,a.error,a.data action_data FROM copy_events e LEFT JOIN copy_actions a ON a.event_id=e.id ORDER BY e.detected_at DESC LIMIT 100");
 const comparison=rows.map(r=>{const t=decode(r.target_data),a=decode(r.action_data);return {target_tx:r.hash,target_side:r.kind,token:t.token,target_bnb_raw:t.quote_token==='0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'?t.quote_raw:null,target_bnb_evidence:t.quote_estimate??t.quote_evidence_method,target_tokens_raw:t.quantity_raw,target_execution_price:t.price_quote??null,first_seen:t.timings?.target_tx_first_seen_at??r.detected_at,source:t.detection_source??t.method,our_mode:r.mode,our_copy_size_raw:a.fill?.input_raw??a.quote?.amount_raw,our_quote_price:a.comparison?.our_price_bnb??null,our_fill_price:a.fill?.price_bnb??null,our_output_raw:a.fill?.output_raw,status:r.state??r.target_status,detection_success:!!t.side,execution_success:r.state==='FILLED',reason:r.error??t.reason,detection_ms:t.detection_source==='MEMPOOL'?t.pending_detection_ms:t.block_detection_ms,reaction_ms:a.paper_reaction_ms??null,price_gap_pct:a.comparison?.price_gap_pct??null,realized_pnl_raw:a.fill?.pnl_raw??null,timings:a.timings??t.timings,historical:!!t.history,late:!!t.late,tax_model:a.paper_model?.tax??null};});
 return {render_provider_benchmark:await store.setting('copy_render_provider_benchmark'),latency_profile:await latencyProfileSummary(store),rpc_telemetry:await store.setting('copy_rpc_telemetry'),backfill:await store.setting('copy_backfill'),latencies_v2:latencies,latency_clock:'MONOTONIC_LOCAL; excludes historical replay; no chain-to-mempool latency claim',target_tx_capture_rate:await store.setting('copy_capture_audit'),source_transactions:sources,target_vs_copy:comparison,self_test:await store.setting('copy_self_test')};
}
