import {FLAP_PORTAL,flapEvidence,hasFlapEvent} from './flap.mjs';
import {BSC,ERC20,PAIR,FACTORY,V3FACTORY,TRANSFER,V2_SWAP,V3_SWAP,PANCAKE_V3_SWAP,addr,hex,transferDeltas,sellFraction,check,packed,cleanError} from '../../core/copy/common.mjs';
export async function decodeTarget(rpc,tx,receipt,block,target,{metadataCache=new Map(),poolCache=new Map()}={}){
 const wallet=addr(target),base={hash:tx.hash,block:Number(BigInt(receipt.blockNumber)),block_hash:receipt.blockHash,tx_index:Number(BigInt(receipt.transactionIndex)),target_at:Number(BigInt(block.timestamp))*1000,timestamp_precision:'BLOCK_SECONDS_NOT_TX_ARRIVAL',router:tx.to?addr(tx.to):null,gas_raw:(BigInt(receipt.gasUsed)*BigInt(receipt.effectiveGasPrice??tx.gasPrice??0)).toString(),from:addr(tx.from),token:null,side:null,kind:'UNKNOWN',reason:null};
 if(receipt.status!=='0x1')return {...base,kind:'FAILED',reason:'TARGET_REVERTED'};
 const deltas=transferDeltas(receipt,wallet),flows=[...deltas].map(([token,delta])=>({token,delta_raw:delta.toString()}));
 if(tx.input?.slice(0,10)==='0x095ea7b3'&&base.from===wallet)return {...base,kind:'APPROVAL',flows};
 if(base.router===BSC.wbnb&&['0xd0e30db0','0x2e1a7d4d'].includes(tx.input?.slice(0,10)))return {...base,kind:'WRAP_UNWRAP',flows};
 const swapLogs=(receipt.logs??[]).filter(l=>[V2_SWAP,V3_SWAP,PANCAKE_V3_SWAP].includes(l.topics?.[0]));
 if(!swapLogs.length&&!hasFlapEvent(receipt))return {...base,kind:flows.length?'TRANSFER':'UNKNOWN',flows,reason:'NO_SUPPORTED_SWAP_EVIDENCE'};
 // The sender must be the watched wallet. Transfers to it from someone else's swap are not buys.
 if(base.from!==wallet)return {...base,kind:'TRANSFER',flows,reason:'TARGET_NOT_TRANSACTION_SENDER'};
 const quotes=new Set([BSC.wbnb,BSC.usdt,BSC.usdc]);const assets=[...deltas].filter(([t])=>!quotes.has(t));if(assets.length!==1)return {...base,flows,reason:'MULTI_ASSET_OR_QUOTE_ONLY'};
 const [token,delta]=assets[0];const metadata=metadataCache.get(token)??await (await import('./rpc.mjs')).tokenMetadata(rpc,token);metadataCache.set(token,metadata);
 const flap=flapEvidence(tx,receipt,block,wallet,token,delta);if(flap)Object.assign(base,{protocol:'FLAP',observed_side:flap.side,protocol_evidence:flap});
 const pools=flap?[{address:FLAP_PORTAL,adapter:'FLAP_PORTAL',token}]: (await Promise.all(swapLogs.map(async log=>{try{const cacheKey=addr(log.address)+':'+log.topics[0];const cached=poolCache.get(cacheKey);if(cached&&Date.now()-cached.at<600000)return cached.pool;const [[token0],[token1],[factory]]=await Promise.all([rpc.contract(log.address,PAIR,'token0'),rpc.contract(log.address,PAIR,'token1'),rpc.contract(log.address,PAIR,'factory')]);const f=addr(factory);let registered,fee=null;if(log.topics[0]===V2_SWAP&&f===BSC.factory)[registered]=await rpc.contract(f,FACTORY,'getPair',[token0,token1]);else if(log.topics[0]===PANCAKE_V3_SWAP&&f===BSC.v3factory){[fee]=await rpc.contract(log.address,PAIR,'fee');[registered]=await rpc.contract(f,V3FACTORY,'getPool',[token0,token1,fee]);}check(registered&&addr(registered)===addr(log.address),'POOL_FACTORY_NOT_AUTHENTICATED');const pool={address:addr(log.address),token0:addr(token0),token1:addr(token1),factory:f,fee:fee===null?null:Number(fee),adapter:log.topics[0]===V2_SWAP?'PANCAKE_V2':'PANCAKE_V3'};poolCache.set(cacheKey,{pool,at:Date.now()});return pool;}catch{return null;}}))).filter(Boolean);
 if(!flap&&!pools.some(p=>[p.token0,p.token1].includes(token)))return {...base,token,...metadata,flows,pools,reason:'SWAP_POOL_NOT_VERIFIED'};
 let quoteToken=null,quoteRaw=null;for(const q of quotes){const d=deltas.get(q)??0n;if(delta>0n&&d<0n||delta<0n&&d>0n){if(quoteToken)return {...base,token,flows,reason:'MULTIPLE_QUOTE_ASSETS'};quoteToken=q;quoteRaw=d<0n?-d:d;}}
 let nativeExact=false;
 // Native BNB amounts are exact only with a trace of this transaction, not a whole-block balance delta.
 if(!quoteToken){try{const trace=await rpc.call('debug_traceTransaction',[tx.hash,{tracer:'callTracer',tracerConfig:{onlyTopCall:false}}]);check(trace&&!trace.error,'TRACE_UNAVAILABLE');let net=0n;function visit(call){if(call.error)return;const value=BigInt(call.value??0);if(value&&['CALL','CREATE','CREATE2','SELFDESTRUCT'].includes(call.type??'CALL')){if(call.from&&addr(call.from)===wallet)net-=value;if(call.to&&addr(call.to)===wallet)net+=value;}for(const child of call.calls??[])visit(child);}visit(trace);if(delta>0n&&net<0n||delta<0n&&net>0n){quoteToken=BSC.wbnb;quoteRaw=net<0n?-net:net;nativeExact=true;}if(!quoteToken)base.quote_evidence_error='TRACE_WITHOUT_VERIFIABLE_NATIVE_FLOW';}catch(error){base.quote_evidence_error=cleanError(error);base.quote_evidence_method='debug_traceTransaction';if(delta>0n&&BigInt(tx.value)>0n){quoteToken=BSC.wbnb;quoteRaw=BigInt(tx.value);base.quote_estimate='TX_VALUE_UPPER_BOUND_INCLUDES_ROUTER_FEES';}}}

 if(!quoteToken||!quoteRaw)return {...base,token,...metadata,flows,pools,quantity_raw:(delta>0n?delta:-delta).toString(),kind:flap?'OBSERVED_'+flap.side:base.kind,reason:'QUOTE_AMOUNT_NOT_VERIFIABLE'};
 const out={...base,token,...metadata,flows,pools,quote_token:quoteToken,quote_raw:quoteRaw.toString(),quantity_raw:(delta>0n?delta:-delta).toString(),side:delta>0n?'BUY':'SELL',kind:delta>0n?'BUY':'SELL',native_balance_evidence:nativeExact,price_quote:Number(quoteRaw)/1e18/(Number(delta>0n?delta:-delta)/10**metadata.decimals),target_balance_before:null,sold_fraction:null};
 if(delta<0n){try{const h=Number(BigInt(receipt.blockNumber));const [balance]=await rpc.contract(token,ERC20,'balanceOf',[wallet],hex(h-1));let before=BigInt(balance);const logs=await rpc.call('eth_getLogs',[{address:token,fromBlock:hex(h),toBlock:hex(h),topics:[TRANSFER]}]);for(const log of logs){if(Number(BigInt(log.transactionIndex))>=out.tx_index)continue;const t=ERC20.parseLog(log);if(addr(t.args.to)===wallet)before+=t.args.value;if(addr(t.args.from)===wallet)before-=t.args.value;}out.target_balance_before=before.toString();out.sold_fraction=sellFraction(before,-delta);out.kind=out.sold_fraction>=.999999?'FULL_EXIT':'PARTIAL_SELL';}catch{out.exit_evidence='HISTORICAL_BALANCE_UNAVAILABLE';}}
 return out;
}
