import {localV2AmountOut} from './route-metadata.mjs';
import {PaperDexRoute} from './paper-dex-route.mjs';
import {selectQuote} from './quote-selection.mjs';
import {FlapRoute} from './flap.mjs';
import {PancakeSmartRoute} from './smart-routes.mjs';
import {BSC,ERC20,ROUTER,PAIR,FACTORY,addr,hex,check,mergePools} from '../../core/copy/common.mjs';
export class PancakeV2Route {
 constructor(rpc){this.rpc=rpc;this.id='PANCAKE_V2';this.verifiedAt=0;}
 async verify(){if(Date.now()-this.verifiedAt<600000)return;await this.rpc.verify();const [[w],[f]]=await Promise.all([this.rpc.contract(BSC.router,ROUTER,'WETH'),this.rpc.contract(BSC.router,ROUTER,'factory')]);check(addr(w)===BSC.wbnb&&addr(f)===BSC.factory,'PANCAKE_DEPLOYMENT_MISMATCH');this.verifiedAt=Date.now();}
 async quote({side,token,amount,slippageBps,taker}){
  await this.verify();const start=performance.now(),quoteBlock=await this.rpc.call('eth_blockNumber');
  const input=side==='BUY'?BSC.wbnb:token,output=side==='BUY'?token:BSC.wbnb,paths=[[input,output],[input,BSC.usdt,output]];
  const attempts=await Promise.allSettled(paths.map(async path=>{
   const pairs=await Promise.all(path.slice(1).map(async(_,i)=>{const [pair]=await this.rpc.contract(BSC.factory,FACTORY,'getPair',[path[i],path[i+1]]);check(BigInt(pair)!==0n,'NO_POOL');return pair;}));
   const states=await Promise.all(pairs.map(pair=>Promise.all([this.rpc.contract(pair,PAIR,'getReserves',[],quoteBlock),this.rpc.contract(pair,PAIR,'token0')])));
   const priceAt=Date.now(),cpu=performance.now();let mid=1,out=BigInt(amount),nativeLiquidity=null,tokenStableLiquidity=null;const pools=[];
   for(let i=0;i<pairs.length;i++){
    const [[r0,r1],[t0]]=states[i],forward=addr(t0)===addr(path[i]),ri=forward?r0:r1,ro=forward?r1:r0;check(ri>0n&&ro>0n,'EMPTY_POOL');
    out=localV2AmountOut(out,ri,ro);mid*=Number(ro)/Number(ri);pools.push(addr(pairs[i]));
    if(path[i]===BSC.wbnb)nativeLiquidity=Number(ri)/1e18*2;if(path[i+1]===BSC.wbnb)nativeLiquidity=Number(ro)/1e18*2;
    if(path[i]===token&&path[i+1]===BSC.usdt)tokenStableLiquidity=Number(ro)/1e18*2;if(path[i+1]===token&&path[i]===BSC.usdt)tokenStableLiquidity=Number(ri)/1e18*2;
   }
   return {path,pools,out:String(out),impact:Math.max(0,(1-Number(out)/(Number(amount)*mid))*100),nativeLiquidity:tokenStableLiquidity===null?nativeLiquidity:null,tokenStableLiquidity,priceAt,local_quote_cpu_ms:performance.now()-cpu};
  }));
  const candidates=attempts.filter(r=>r.status==='fulfilled').map(r=>r.value);check(candidates.length,'NO_PANCAKE_V2_ROUTE');candidates.sort((a,b)=>BigInt(a.out)>BigInt(b.out)?-1:1);
  const best=candidates[0],gasPrice=BigInt(await this.rpc.call('eth_gasPrice'));
  return {provider:this.id,side,token,amount_raw:String(amount),out_raw:best.out,min_out_raw:String(BigInt(best.out)*BigInt(10000-slippageBps)/10000n),impact_pct:best.impact,slippage_bps:slippageBps,route:best.path,pools:best.pools,liquidity_bnb:best.nativeLiquidity,liquidity_usd:best.tokenStableLiquidity,quote_block:quoteBlock,gas_price:String(gasPrice),estimated_gas:side==='BUY'?'240000':'280000',gas_estimate_source:'CONSERVATIVE_UNTIL_ETH_ESTIMATE_GAS',fee_raw:String(gasPrice*BigInt(side==='BUY'?240000:280000)),quoted_at:best.priceAt,quote_ms:performance.now()-start,candidates,recipient:taker,tax_adjusted:false,quote_calculation:'CANONICAL_PANCAKE_V2_LOCAL_FRESH_RESERVES',local_quote_cpu_ms:best.local_quote_cpu_ms};
 }
 async build(q,taker,config){const deadline=Math.floor(Date.now()/1000)+config.deadline_seconds;const buy=q.side==='BUY';let approval=null;if(!buy){const [allowance]=await this.rpc.contract(q.token,ERC20,'allowance',[taker,BSC.router]);if(allowance<BigInt(q.amount_raw))approval={token:q.token,spender:BSC.router,amount_raw:q.amount_raw,reset:allowance>0n};}const tx={from:taker,to:BSC.router,data:buy?ROUTER.encodeFunctionData('swapExactETHForTokensSupportingFeeOnTransferTokens',[q.min_out_raw,q.route,taker,deadline]):ROUTER.encodeFunctionData('swapExactTokensForETHSupportingFeeOnTransferTokens',[q.amount_raw,q.min_out_raw,q.route,taker,deadline]),value:buy?hex(q.amount_raw):'0x0'};return {tx,approval,deadline,provider:this.id};}
}
export class ZeroExRoute {
 constructor(rpc,key){this.rpc=rpc;this.key=key;this.id='ZEROX_ALLOWANCE_HOLDER';}
 async quote({side,token,amount,slippageBps,taker,signal,paper=false}){check(this.key,'ZEROX_KEY_NOT_CONFIGURED');const start=performance.now();const params=new URLSearchParams({chainId:'56',sellToken:side==='BUY'?BSC.native:token,buyToken:side==='BUY'?token:BSC.native,sellAmount:String(amount),...(paper?{}:{taker,recipient:taker}),slippageBps:String(slippageBps)});const r=await fetch('https://api.0x.org/swap/allowance-holder/'+(paper?'price':'quote')+'?'+params,{headers:{'0x-api-key':this.key,'0x-version':'v2'},signal:signal?AbortSignal.any([signal,AbortSignal.timeout(2500)]):AbortSignal.timeout(2500)});check(r.ok,'ZEROX_HTTP_'+r.status);const j=await r.json();check(j.liquidityAvailable&&BigInt(j.buyAmount)>0n,'ZEROX_NO_LIQUIDITY');if(!paper){check(addr(j.transaction?.to)===BSC.holder,'ZEROX_ENTRYPOINT_NOT_ALLOWED');if(j.issues?.allowance?.spender)check(addr(j.issues.allowance.spender)===BSC.holder,'ZEROX_SPENDER_NOT_ALLOWED');check(BigInt(j.transaction.value??0)===(side==='BUY'?BigInt(amount):0n),'ZEROX_VALUE_MISMATCH');}check(BigInt(j.minBuyAmount)>0n&&BigInt(j.minBuyAmount)<=BigInt(j.buyAmount),'ZEROX_INVALID_MINIMUM');check(BigInt(j.minBuyAmount)>=BigInt(j.buyAmount)*BigInt(10000-slippageBps)/10000n,'ZEROX_SLIPPAGE_EXCEEDS_LIMIT');const gas=BigInt((paper?j.gas:j.transaction.gas)??0),gasPrice=BigInt((paper?j.gasPrice:j.transaction.gasPrice)??await this.rpc.call('eth_gasPrice'));check(gas>0n,'ZEROX_GAS_UNKNOWN');return {provider:this.id,side,token,amount_raw:String(amount),out_raw:j.buyAmount,min_out_raw:j.minBuyAmount,impact_pct:null,slippage_bps:slippageBps,route:j.route,pools:[],fee_raw:(gas*gasPrice).toString(),gas_price:gasPrice.toString(),estimated_gas:gas.toString(),quoted_at:Date.now(),quote_ms:performance.now()-start,transaction:paper?null:j.transaction,paper_indicative:paper,fees:j.fees,issues:j.issues,token_metadata:j.tokenMetadata,recipient:taker,tax_adjusted:true,live_supported:false,live_block:'0x calldata recipient/amount decoder and native proceeds reconciliation not yet independently validated'};}
 async build(q,taker){return {tx:{from:taker,to:q.transaction.to,data:q.transaction.data,value:hex(q.transaction.value??0)},approval:q.issues?.allowance?{token:q.token,spender:BSC.holder,amount_raw:q.amount_raw}:null,deadline:Math.floor(q.quoted_at/1000)+20,provider:this.id};}
}
export class RouteEngine {
 constructor(rpc,keys={}){this.rpc=rpc;this.hints=new Map();this.providers=[new PancakeV2Route(rpc),new PancakeSmartRoute(rpc),new PaperDexRoute(rpc),new FlapRoute(rpc),...(keys.zeroEx?[new ZeroExRoute(rpc,keys.zeroEx)]:[])];}
 async quote(request,options={}){const {live=false}=options;const hints=mergePools(this.hints.get(request.token),request.hints);if(hints.length)this.hints.set(request.token,hints);request={...request,hints};const selected=this.providers.filter(p=>(p.id!=='PAPER_DEX_PATH'||request.paper)&&(!live||['PANCAKE_V2','PANCAKE_SMART'].includes(p.id))&&(p.id!=='FLAP_PORTAL'||hints.some(h=>h.adapter==='FLAP_PORTAL')));if(request.paper&&request.prefetchedQuote)selected.push({id:'MEMPOOL_PREFETCH',quote:async()=>{const q=await request.prefetchedQuote;check(q.side===request.side&&q.token===request.token&&q.amount_raw===String(request.amount),'PREFETCH_TERMS_CHANGED');return q;}});const flap=selected.find(p=>p.id==='FLAP_PORTAL');if(request.paper&&flap&&!hints.some(h=>h.adapter!=='FLAP_PORTAL')){try{return await selectQuote([flap],request,{...options,rpc:this.rpc});}catch(error){const q=await selectQuote(selected.filter(p=>p!==flap),request,{...options,rpc:this.rpc});return {...q,route_errors:[...(error.route_errors??[]),...(q.route_errors??[])]};}}return selectQuote(selected,request,{...options,rpc:this.rpc});}
 build(q,taker,config){return this.providers.find(p=>p.id===q.provider).build(q,taker,config);}
 async bnbUsd(){const [out]=await this.rpc.contract(BSC.router,ROUTER,'getAmountsOut',[10n**18n,[BSC.wbnb,BSC.usdt]]);return {value:Number(out.at(-1))/1e18,at:Date.now(),source:'Pancake V2 WBNB/USDT quote; assumes USDT USD peg',peg_assumption:true};}
}
