import {BSC,check,encode,cleanError,hex} from '../../core/copy/common.mjs';
export class BscRpc {
 constructor(providers,{timeout=4000,fetcher=fetch}={}){this.providers=providers.filter(p=>p.enabled);this.timeout=timeout;this.fetcher=fetcher;this.sequence=0;this.verified=new Set();this.cooldown=new Map();this.metrics=[];}
 async request(provider,method,params=[],timeout=this.timeout){if(method!=='eth_chainId'&&!this.verified.has(provider.id)){const chain=await this.request(provider,'eth_chainId',[],timeout);check(Number(BigInt(chain))===56,'WRONG_CHAIN_ID');this.verified.add(provider.id);}const start=performance.now();const until=this.cooldown.get(provider.id)??0;check(Date.now()>=until,'RPC_BACKOFF');try{const r=await this.fetcher(provider.http_url,{method:'POST',headers:{'Content-Type':'application/json'},body:encode({jsonrpc:'2.0',id:++this.sequence,method,params}),signal:AbortSignal.timeout(timeout)});if(r.status===429||r.status===503){this.cooldown.set(provider.id,Date.now()+Math.max(3000,Number(r.headers.get('retry-after')??3)*1000));throw Error('RPC_HTTP_'+r.status);}check(r.ok,'RPC_HTTP_'+r.status);const data=await r.json();check(!data.error,'RPC_'+data.error?.code+': '+String(data.error?.message??'').slice(0,140));check(Object.hasOwn(data,'result'),'RPC_MALFORMED');if(method==='eth_chainId'){check(Number(BigInt(data.result))===56,'WRONG_CHAIN_ID');this.verified.add(provider.id);}this.metrics.push({provider:provider.id,method,at:Date.now(),duration_ms:performance.now()-start,status:'OK'});return data.result;}catch(e){this.metrics.push({provider:provider.id,method,at:Date.now(),duration_ms:performance.now()-start,status:'ERROR',error:cleanError(e)});throw e;}finally{if(this.metrics.length>300)this.metrics.splice(0,this.metrics.length-300);}}
 async call(method,params=[],{timeout,provider}={}){if(provider)return this.request(provider,method,params,timeout);let error;for(const p of this.providers){try{return await this.request(p,method,params,timeout);}catch(e){error=e;if(method==='eth_sendRawTransaction')throw e;}}throw error??Error('BSC_PROVIDER_NOT_CONFIGURED');}
 async verify(){const chain=await this.call('eth_chainId');check(Number(BigInt(chain))===BSC.chainId,'WRONG_CHAIN_ID');return Number(BigInt(await this.call('eth_blockNumber')));}
 async contract(to,abi,method,args=[],block='latest'){const out=await this.call('eth_call',[{to,data:abi.encodeFunctionData(method,args)},block]);return abi.decodeFunctionResult(method,out);}
 async benchmark(){const results=await Promise.allSettled(this.providers.map(async p=>{const start=performance.now();const chain=await this.request(p,'eth_chainId');check(Number(BigInt(chain))===56,'WRONG_CHAIN_ID');const block=await this.request(p,'eth_getBlockByNumber',['latest',false]);return {provider:p.id,chain_id:56,block:Number(BigInt(block.number)),block_at:Number(BigInt(block.timestamp))*1000,received_at:Date.now(),duration_ms:performance.now()-start,method:'HTTP chainId + latest block'};}));return results.map((r,i)=>r.status==='fulfilled'?r.value:{provider:this.providers[i].id,error:cleanError(r.reason)});}
}
export async function tokenMetadata(rpc,token){const {ERC20}=await import('../../core/copy/common.mjs');const [[d],s]=await Promise.all([rpc.contract(token,ERC20,'decimals'),rpc.contract(token,ERC20,'symbol').catch(()=>[null])]);check(Number(d)<=36,'UNSUPPORTED_DECIMALS');return {decimals:Number(d),symbol:s[0]??token.slice(0,8)};}
export const blockTag=n=>hex(n);
