import {BSC,SMART_ROUTER,QUOTER_V3,V3POOL,ERC20,PAIR,FACTORY,V3FACTORY,ROUTER,addr,hex,v3Path,check} from '../../core/copy/common.mjs';
import {smartCalls} from '../../core/copy/smart-router.mjs';
export function routePaths(pools,input,output){const paths=[];function walk(token,hops,seen){if(token===output){if(hops.some(h=>h.adapter==='PANCAKE_V3'))paths.push(hops);return;}if(hops.length>=4)return;for(const p of pools){if(![p.token0,p.token1].includes(token))continue;const next=p.token0===token?p.token1:p.token0;if(seen.has(next))continue;walk(next,[...hops,{adapter:p.adapter,tokenIn:token,tokenOut:next,fee:p.fee,pool:p.address}],new Set([...seen,next]));}}walk(input,[],new Set([input]));return paths.slice(0,6);}
export class PancakeSmartRoute {
 constructor(rpc){this.rpc=rpc;this.id='PANCAKE_SMART';this.cache=new Map();this.verifiedAt=0;}
 async verify(){if(Date.now()-this.verifiedAt<600000)return;await this.rpc.verify();const [[w],[f],[v3]]=await Promise.all([this.rpc.contract(BSC.smartRouter,SMART_ROUTER,'WETH9'),this.rpc.contract(BSC.smartRouter,SMART_ROUTER,'factoryV2'),this.rpc.contract(BSC.smartRouter,SMART_ROUTER,'factory')]);check(addr(w)===BSC.wbnb&&addr(f)===BSC.factory&&addr(v3)===BSC.v3factory,'SMART_DEPLOYMENT_MISMATCH');this.verifiedAt=Date.now();}
 async authenticate(h){const key=h.pool+':'+h.tokenIn+':'+h.tokenOut+':'+h.fee;if(Date.now()-(this.cache.get(key)??0)<600000)return;const [[t0],[t1],[f]]=await Promise.all(['token0','token1','factory'].map(m=>this.rpc.contract(h.pool,PAIR,m)));check([addr(t0),addr(t1)].includes(h.tokenIn)&&[addr(t0),addr(t1)].includes(h.tokenOut),'SMART_POOL_ASSETS');const factory=h.adapter==='PANCAKE_V3'?BSC.v3factory:BSC.factory;check(addr(f)===factory,'SMART_FACTORY');const [pool]=h.adapter==='PANCAKE_V3'?await this.rpc.contract(factory,V3FACTORY,'getPool',[h.tokenIn,h.tokenOut,h.fee]):await this.rpc.contract(factory,FACTORY,'getPair',[h.tokenIn,h.tokenOut]);check(addr(pool)===addr(h.pool),'SMART_POOL_NOT_REGISTERED');this.cache.set(key,Date.now());}
 async quote({side,token,amount,slippageBps,taker,hints=[]}){
 let paths=routePaths(hints,side==='BUY'?BSC.wbnb:token,side==='BUY'?token:BSC.wbnb);if(!paths.length&&hints.some(p=>p.adapter==='PANCAKE_V3')){const bridges=await Promise.all([BSC.usdt,BSC.usdc].map(async stable=>{try{const [pool]=await this.rpc.contract(BSC.factory,FACTORY,'getPair',[BSC.wbnb,stable]);return BigInt(pool)>0n?{address:addr(pool),token0:BSC.wbnb,token1:stable,adapter:'PANCAKE_V2',fee:null}:null;}catch{return null;}}));paths=routePaths([...hints,...bridges.filter(Boolean)],side==='BUY'?BSC.wbnb:token,side==='BUY'?token:BSC.wbnb);}check(paths.length,'NO_AUTHENTICATED_V3_ROUTE_HINT');await this.verify();const start=performance.now();await Promise.all(paths.flat().map(h=>this.authenticate(h)));const block=await this.rpc.call('eth_blockNumber');const gasPrice=BigInt(await this.rpc.call('eth_gasPrice'));
 const attempts=await Promise.allSettled(paths.map(async hops=>{let out=BigInt(amount),mid=1,quotedAt=0,gas=90000n;for(const h of hops){let price;if(h.adapter==='PANCAKE_V3'){const [[next,,,estimate],[sqrt],[t0]]=await Promise.all([this.rpc.contract(BSC.quoterV3,QUOTER_V3,'quoteExactInput',[v3Path([h.tokenIn,h.tokenOut],[h.fee]),out],block),this.rpc.contract(h.pool,V3POOL,'slot0',[],block),this.rpc.contract(h.pool,PAIR,'token0')]);out=next;gas+=estimate;const ratio=(Number(sqrt)/2**96)**2;price=addr(t0)===h.tokenIn?ratio:1/ratio;}else{const [[amounts],[r0,r1],[t0]]=await Promise.all([this.rpc.contract(BSC.router,ROUTER,'getAmountsOut',[out,[h.tokenIn,h.tokenOut]],block),this.rpc.contract(h.pool,PAIR,'getReserves',[],block),this.rpc.contract(h.pool,PAIR,'token0')]);out=amounts.at(-1);gas+=110000n;price=addr(t0)===h.tokenIn?Number(r1)/Number(r0):Number(r0)/Number(r1);}if(!quotedAt)quotedAt=Date.now();mid*=price;check(out>0n&&Number.isFinite(mid)&&mid>0,'SMART_QUOTE_INVALID');}return {hops,out,impact:Math.max(0,(1-Number(out)/(Number(amount)*mid))*100),quotedAt,gas:gas*130n/100n};}));
 const valid=attempts.filter(r=>r.status==='fulfilled').map(r=>r.value).sort((a,b)=>a.out>b.out?-1:1);check(valid.length,'SMART_NO_QUOTE');const best=valid[0];return {provider:this.id,side,token,amount_raw:String(amount),out_raw:String(best.out),min_out_raw:String(best.out*BigInt(10000-slippageBps)/10000n),impact_pct:best.impact,slippage_bps:slippageBps,route:[best.hops[0].tokenIn,...best.hops.map(h=>h.tokenOut)],hops:best.hops,pools:best.hops.map(h=>h.pool),liquidity_bnb:null,liquidity_usd:null,liquidity_source:'UNKNOWN_V3_ACTIVE_LIQUIDITY_USD',gas_price:String(gasPrice),estimated_gas:String(best.gas),fee_raw:String(gasPrice*best.gas),gas_estimate_source:'QUOTER_PLUS_CONSERVATIVE_OVERHEAD_UNTIL_SIMULATION',quote_block:block,quoted_at:best.quotedAt,quote_ms:performance.now()-start,recipient:taker,tax_adjusted:false};
 }
 async build(q,taker,c){const deadline=Math.floor(Date.now()/1000)+c.deadline_seconds;let approval=null;if(q.side==='SELL'){const [n]=await this.rpc.contract(q.token,ERC20,'allowance',[taker,BSC.smartRouter]);if(n<BigInt(q.amount_raw))approval={token:q.token,spender:BSC.smartRouter,amount_raw:q.amount_raw,reset:n>0n};}return {tx:{from:taker,to:BSC.smartRouter,value:q.side==='BUY'?hex(q.amount_raw):'0x0',data:SMART_ROUTER.encodeFunctionData('multicall',[deadline,smartCalls(q,taker,deadline)])},approval,deadline,provider:this.id};}
}
