import {Interface,Transaction,keccak256,getAddress} from 'ethers';
import {rpc,fail,digest} from '../util.mjs';
import {RH,EvmAdapter} from '../providers/chains.mjs';
const routerABI=new Interface(['function WETH() view returns(address)','function factory() view returns(address)','function getAmountsOut(uint256,address[]) view returns(uint256[])','function swapExactTokensForTokens(uint256,uint256,address[],address,uint256) returns(uint256[])']);
const erc20=new Interface(['function allowance(address,address) view returns(uint256)','function approve(address,uint256) returns(bool)','function balanceOf(address) view returns(uint256)','event Transfer(address indexed from,address indexed to,uint256 value)']);
const factoryABI=new Interface(['function getPair(address,address) view returns(address)']);
const pairABI=new Interface(['function getReserves() view returns(uint112,uint112,uint32)','function token0() view returns(address)']);
const hex=n=>'0x'+BigInt(n).toString(16);
export class UniswapV2Executor {
 constructor(chain){this.chain=chain;this.adapter=new EvmAdapter(chain);}
 async call(to,abi,name,args=[]){const v=await this.adapter.rpc('eth_call',[{to,data:abi.encodeFunctionData(name,args)},'latest']);return abi.decodeFunctionResult(name,v);}
 async quote(inputMint,outputMint,amount,slippageBps){fail(this.chain.id==='robinhood','ROBINHOOD_MAINNET_V2_ONLY');await this.adapter.health();fail(await this.adapter.rpc('eth_getCode',[RH.router,'latest'])!=='0x','ROUTER_NOT_DEPLOYED');const [factory]=await this.call(RH.router,routerABI,'factory');fail(factory.toLowerCase()===RH.factory.toLowerCase(),'ROUTER_FACTORY_MISMATCH');const [weth]=await this.call(RH.router,routerABI,'WETH');fail(weth.toLowerCase()===RH.weth.toLowerCase(),'ROUTER_WETH_MISMATCH');const paths=[[inputMint,outputMint]];if(![inputMint,outputMint].some(a=>a.toLowerCase()===RH.weth.toLowerCase()))paths.push([inputMint,RH.weth,outputMint]);const candidates=[];
 for(const path of paths){try{const [amounts]=await this.call(RH.router,routerABI,'getAmountsOut',[BigInt(amount),path]);let mid=1;const pools=[];for(let n=0;n<path.length-1;n++){const [pair]=await this.call(RH.factory,factoryABI,'getPair',[path[n],path[n+1]]);fail(pair!=='0x0000000000000000000000000000000000000000','POOL_UNAVAILABLE');const [[r0,r1],[t0]]=await Promise.all([this.call(pair,pairABI,'getReserves'),this.call(pair,pairABI,'token0')]);const forward=t0.toLowerCase()===path[n].toLowerCase();const ri=forward?r0:r1,ro=forward?r1:r0;fail(ri>0n&&ro>0n,'POOL_EMPTY');mid*=Number(ro)/Number(ri);pools.push(pair);}const out=amounts.at(-1);const impact=(1-Number(out)/(Number(amount)*mid))*100;candidates.push({path,pools,out:out.toString(),priceImpactPct:impact});}catch{}}
 fail(candidates.length,'ROUTE_UNAVAILABLE');candidates.sort((a,b)=>BigInt(a.out)>BigInt(b.out)?-1:1);const best=candidates[0];return {provider:'Uniswap V2 · Robinhood',inputMint,outputMint,inAmount:amount,outAmount:best.out,minOut:(BigInt(best.out)*BigInt(10000-slippageBps)/10000n).toString(),slippageBps,priceImpactPct:best.priceImpactPct,route:best.path,pools:best.pools,candidates,selectionReason:'Highest output; same router and bounded hop count. Gas is checked before signing.',quotedAt:Date.now()};}
 async build(q,wallet){const [allowance]=await this.call(q.inputMint,erc20,'allowance',[wallet,RH.router]);const approval=allowance<BigInt(q.inAmount);const deadline=Math.floor(Date.now()/1000)+90;const tx={from:wallet,to:approval?q.inputMint:RH.router,data:approval?erc20.encodeFunctionData('approve',[RH.router,BigInt(q.inAmount)]):routerABI.encodeFunctionData('swapExactTokensForTokens',[BigInt(q.inAmount),BigInt(q.minOut),q.route,wallet,deadline]),value:'0x0'};const result=await this.adapter.rpc('eth_call',[tx,'pending']);const estimated=await this.adapter.rpc('eth_estimateGas',[tx]);const gas=BigInt(estimated)*120n/100n;const gasPrice=BigInt(await this.adapter.rpc('eth_gasPrice'));const nonce=await this.adapter.rpc('eth_getTransactionCount',[wallet,'pending']);const unsigned={...tx,chainId:this.chain.chain_id,nonce:parseInt(nonce,16),gasLimit:gas.toString(),gasPrice:gasPrice.toString(),type:0};delete unsigned.from;return {unsigned:JSON.stringify(unsigned),messageDigest:await digest(JSON.stringify(unsigned)),approval,deadline,feeRaw:(gas*gasPrice).toString(),feeAsset:RH.weth,feeDecimals:18,simulation:{result,estimatedGas:estimated,method:'eth_call + eth_estimateGas',block:'pending'}};}
 async validateSigned(build,payload,wallet){const t=Transaction.from(payload);const intended=JSON.parse(build.unsigned);fail(t.from?.toLowerCase()===wallet.toLowerCase(),'WRONG_SIGNER');fail(Number(t.chainId)===this.chain.chain_id&&t.nonce===intended.nonce&&t.to?.toLowerCase()===intended.to.toLowerCase()&&t.data===intended.data&&t.value===BigInt(intended.value)&&t.gasLimit===BigInt(intended.gasLimit)&&t.gasPrice===BigInt(intended.gasPrice),'SIGNED_MESSAGE_MISMATCH');return keccak256(payload);}
 broadcast(payload){return this.adapter.rpc('eth_sendRawTransaction',[payload]);}
 async reconcile(order){const r=await this.adapter.receipt(order.signature);if(!r)return {status:'PENDING'};const fee=BigInt(r.gasUsed)*BigInt(r.effectiveGasPrice??'0x0');if(r.status!=='0x1')return {status:'FAILED_ONCHAIN',feeRaw:fee.toString(),block:String(parseInt(r.blockNumber,16)),raw:r};const build=JSON.parse(order.build);if(build.approval)return {status:'APPROVAL_CONFIRMED',feeRaw:fee.toString(),block:String(parseInt(r.blockNumber,16)),raw:r};let input=0n,output=0n;for(const log of r.logs){try{const t=erc20.parseLog(log);if(t?.name!=='Transfer')continue;if(log.address.toLowerCase()===order.input_mint.toLowerCase()&&t.args.from.toLowerCase()===order.wallet.toLowerCase())input+=t.args.value;if(log.address.toLowerCase()===order.output_mint.toLowerCase()&&t.args.to.toLowerCase()===order.wallet.toLowerCase())output+=t.args.value;}catch{}}return {status:input>0n&&output>0n?'RECONCILED':'RECONCILIATION_REQUIRED',inputRaw:input?input.toString():null,outputRaw:output?output.toString():null,feeRaw:fee.toString(),block:String(parseInt(r.blockNumber,16)),raw:r};}
}
