import {Connection,PublicKey,TransactionInstruction,TransactionMessage,VersionedTransaction,AddressLookupTableAccount,ComputeBudgetProgram} from '@solana/web3.js';
import {http,fail,digest,rpc} from '../util.mjs';
import {SOL,SolanaAdapter} from '../providers/chains.mjs';
const ix=x=>new TransactionInstruction({programId:new PublicKey(x.programId),keys:x.accounts.map(a=>({pubkey:new PublicKey(a.pubkey),isSigner:a.isSigner,isWritable:a.isWritable})),data:Buffer.from(x.data,'base64')});
export class JupiterExecutor {
 constructor(chain,key=null){this.chain=chain;this.key=key;this.adapter=new SolanaAdapter(chain);}
 async quote(inputMint,outputMint,amount,slippageBps,taker=null){fail(this.chain.id==='solana','JUPITER_MAINNET_ONLY');const params=new URLSearchParams({inputMint,outputMint,amount,slippageBps:String(slippageBps),...(taker?{taker}:{})});const raw=await http('https://api.jup.ag/swap/v2/'+(taker?'build':'order')+'?'+params,{headers:this.key?{'x-api-key':this.key}:{}});fail(raw.inputMint===inputMint&&raw.outputMint===outputMint&&String(raw.inAmount)===amount,'QUOTE_INTENT_MISMATCH');fail(raw.outAmount&&raw.otherAmountThreshold,'MALFORMED_QUOTE');return {provider:'Jupiter Swap v2',inputMint,outputMint,inAmount:raw.inAmount,outAmount:raw.outAmount,minOut:raw.otherAmountThreshold,slippageBps:raw.slippageBps,priceImpactPct:raw.priceImpact!==undefined?Number(raw.priceImpact):raw.priceImpactPct!==undefined?Number(raw.priceImpactPct)*100:null,route:raw.routePlan??raw.route??[],quotedAt:Date.now(),raw};}
 async build(q,wallet){const r=q.raw;fail(r.swapInstruction,'NO_BUILD_INSTRUCTIONS');const connection=new Connection(this.chain.rpc_url,'confirmed');const block=await connection.getLatestBlockhash('confirmed');const lookupTables=[];for(const address of Object.keys(r.addressesByLookupTableAddress??{})){const result=await connection.getAddressLookupTable(new PublicKey(address));fail(result.value,'LOOKUP_TABLE_UNAVAILABLE');lookupTables.push(result.value);}
 const supplied=(r.computeBudgetInstructions??[]).map(ix).filter(i=>i.programId.equals(ComputeBudgetProgram.programId)&&i.data[0]===3);for(const i of supplied){const micro=i.data.readBigUInt64LE(1);fail(micro<=1000000n,'PRIORITY_FEE_TOO_HIGH');}
 const instructions=[ComputeBudgetProgram.setComputeUnitLimit({units:1400000}),...supplied,...(r.setupInstructions??[]).map(ix),...(r.otherInstructions??[]).map(ix),ix(r.swapInstruction),...(r.cleanupInstruction?[ix(r.cleanupInstruction)]:[]),...(r.tipInstruction?[ix(r.tipInstruction)]:[])];
 const balanceBefore=(await this.adapter.balance(wallet)).value;const make=()=>new VersionedTransaction(new TransactionMessage({payerKey:new PublicKey(wallet),recentBlockhash:block.blockhash,instructions}).compileToV0Message(lookupTables));let tx=make();let sim=await this.adapter.simulate(Buffer.from(tx.serialize()).toString('base64'),wallet);fail(sim.value?.err===null,'SIMULATION_FAILED: '+JSON.stringify(sim.value?.err));if(sim.value.unitsConsumed){instructions[0]=ComputeBudgetProgram.setComputeUnitLimit({units:Math.min(1400000,Math.ceil(sim.value.unitsConsumed*1.2))});tx=make();sim=await this.adapter.simulate(Buffer.from(tx.serialize()).toString('base64'),wallet);fail(sim.value?.err===null,'FINAL_SIMULATION_FAILED');}
 const fee=await connection.getFeeForMessage(tx.message,'confirmed');fail(fee.value!==null,'NETWORK_FEE_UNKNOWN');const simulatedBalance=sim.value.accounts?.[0]?.lamports;fail(Number.isFinite(simulatedBalance),'SIMULATED_BALANCE_UNAVAILABLE');const nativeInput=q.inputMint===SOL?BigInt(q.inAmount):0n;const nativeOutput=q.outputMint===SOL?BigInt(q.outAmount):0n;const debit=BigInt(balanceBefore)-BigInt(simulatedBalance)-nativeInput+nativeOutput;const totalNativeCostRaw=(debit>BigInt(fee.value)?debit:BigInt(fee.value)).toString();const unsigned=Buffer.from(tx.serialize()).toString('base64');return {unsigned,messageDigest:await digest(tx.message.serialize()),lastValidBlockHeight:block.lastValidBlockHeight,blockhash:block.blockhash,feeRaw:String(fee.value),totalNativeCostRaw,balanceBeforeRaw:String(balanceBefore),simulation:{err:sim.value.err,unitsConsumed:sim.value.unitsConsumed,slot:sim.context.slot,logs:sim.value.logs},feeAsset:SOL,feeDecimals:9};}
 async validateSigned(build,payload,wallet){const tx=VersionedTransaction.deserialize(Buffer.from(payload,'base64'));fail(await digest(tx.message.serialize())===build.messageDigest,'SIGNED_MESSAGE_MISMATCH');const index=tx.message.staticAccountKeys.findIndex(k=>k.toBase58()===wallet);fail(index>=0&&index<tx.message.header.numRequiredSignatures,'WRONG_SIGNER');const key=await crypto.subtle.importKey('raw',tx.message.staticAccountKeys[index].toBytes(),{name:'Ed25519'},false,['verify']);fail(await crypto.subtle.verify('Ed25519',key,tx.signatures[index],tx.message.serialize()),'INVALID_SIGNATURE');const {default:bs58}=await import('bs58');return bs58.encode(tx.signatures[0]);}
 async broadcast(payload){return this.adapter.rpc('sendTransaction',[payload,{encoding:'base64',skipPreflight:false,maxRetries:0,preflightCommitment:'confirmed'}]);}
 async reconcile(order){const status=await this.adapter.rpc('getSignatureStatuses',[[order.signature],{searchTransactionHistory:true}]);const s=status.value?.[0];if(!s||!['confirmed','finalized'].includes(s.confirmationStatus))return {status:'PENDING'};const tx=await this.adapter.transaction(order.signature);if(!tx?.meta)return {status:'PENDING'};const m=tx.meta;if(m.err)return {status:'FAILED_ONCHAIN',feeRaw:String(m.fee),block:String(tx.slot),raw:tx};const sum=(list,mint)=>(list??[]).filter(b=>b.owner===order.wallet&&b.mint===mint).reduce((v,b)=>v+BigInt(b.uiTokenAmount.amount),0n);const delta=mint=>sum(m.postTokenBalances,mint)-sum(m.preTokenBalances,mint);let input=delta(order.input_mint),output=delta(order.output_mint);const accountIndex=tx.transaction.message.accountKeys.findIndex(k=>(typeof k==='string'?k:k.pubkey)===order.wallet);fail(accountIndex>=0,'WALLET_ACCOUNT_MISSING');let rent=0n;const ownedIndexes=new Set([...(m.preTokenBalances??[]),...(m.postTokenBalances??[])].filter(b=>b.owner===order.wallet&&b.mint!==SOL).map(b=>b.accountIndex));for(const index of ownedIndexes){if(m.preBalances[index]===0||m.postBalances[index]===0)rent+=BigInt(m.postBalances[index])-BigInt(m.preBalances[index]);}const nativeDelta=BigInt(m.postBalances[accountIndex])-BigInt(m.preBalances[accountIndex])+BigInt(m.fee)+rent;if(order.input_mint===SOL&&input===0n)input=nativeDelta;if(order.output_mint===SOL&&output===0n)output=nativeDelta;const complete=input<0n&&output>0n;return {status:complete?'RECONCILED':'RECONCILIATION_REQUIRED',inputRaw:input<0n?(-input).toString():null,outputRaw:output>0n?output.toString():null,feeRaw:(BigInt(m.fee)+(rent>0n?rent:0n)).toString(),networkFeeRaw:String(m.fee),rentDeltaRaw:rent.toString(),block:String(tx.slot),raw:tx,reason:complete?null:'Balance attribution incomplete'};}

}
